
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CrmPipelineStage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model CrmPipelineStage
 * 
 */
export type CrmPipelineStageModel = runtime.Types.Result.DefaultSelection<Prisma.$CrmPipelineStagePayload>

export type AggregateCrmPipelineStage = {
  _count: CrmPipelineStageCountAggregateOutputType | null
  _avg: CrmPipelineStageAvgAggregateOutputType | null
  _sum: CrmPipelineStageSumAggregateOutputType | null
  _min: CrmPipelineStageMinAggregateOutputType | null
  _max: CrmPipelineStageMaxAggregateOutputType | null
}

export type CrmPipelineStageAvgAggregateOutputType = {
  order: number | null
}

export type CrmPipelineStageSumAggregateOutputType = {
  order: number | null
}

export type CrmPipelineStageMinAggregateOutputType = {
  id: string | null
  pipelineId: string | null
  name: string | null
  order: number | null
  color: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CrmPipelineStageMaxAggregateOutputType = {
  id: string | null
  pipelineId: string | null
  name: string | null
  order: number | null
  color: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CrmPipelineStageCountAggregateOutputType = {
  id: number
  pipelineId: number
  name: number
  order: number
  color: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CrmPipelineStageAvgAggregateInputType = {
  order?: true
}

export type CrmPipelineStageSumAggregateInputType = {
  order?: true
}

export type CrmPipelineStageMinAggregateInputType = {
  id?: true
  pipelineId?: true
  name?: true
  order?: true
  color?: true
  createdAt?: true
  updatedAt?: true
}

export type CrmPipelineStageMaxAggregateInputType = {
  id?: true
  pipelineId?: true
  name?: true
  order?: true
  color?: true
  createdAt?: true
  updatedAt?: true
}

export type CrmPipelineStageCountAggregateInputType = {
  id?: true
  pipelineId?: true
  name?: true
  order?: true
  color?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CrmPipelineStageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CrmPipelineStage to aggregate.
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmPipelineStages to fetch.
   */
  orderBy?: Prisma.CrmPipelineStageOrderByWithRelationInput | Prisma.CrmPipelineStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CrmPipelineStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmPipelineStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmPipelineStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CrmPipelineStages
  **/
  _count?: true | CrmPipelineStageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CrmPipelineStageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CrmPipelineStageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CrmPipelineStageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CrmPipelineStageMaxAggregateInputType
}

export type GetCrmPipelineStageAggregateType<T extends CrmPipelineStageAggregateArgs> = {
      [P in keyof T & keyof AggregateCrmPipelineStage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCrmPipelineStage[P]>
    : Prisma.GetScalarType<T[P], AggregateCrmPipelineStage[P]>
}




export type CrmPipelineStageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CrmPipelineStageWhereInput
  orderBy?: Prisma.CrmPipelineStageOrderByWithAggregationInput | Prisma.CrmPipelineStageOrderByWithAggregationInput[]
  by: Prisma.CrmPipelineStageScalarFieldEnum[] | Prisma.CrmPipelineStageScalarFieldEnum
  having?: Prisma.CrmPipelineStageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CrmPipelineStageCountAggregateInputType | true
  _avg?: CrmPipelineStageAvgAggregateInputType
  _sum?: CrmPipelineStageSumAggregateInputType
  _min?: CrmPipelineStageMinAggregateInputType
  _max?: CrmPipelineStageMaxAggregateInputType
}

export type CrmPipelineStageGroupByOutputType = {
  id: string
  pipelineId: string
  name: string
  order: number
  color: string | null
  createdAt: Date
  updatedAt: Date
  _count: CrmPipelineStageCountAggregateOutputType | null
  _avg: CrmPipelineStageAvgAggregateOutputType | null
  _sum: CrmPipelineStageSumAggregateOutputType | null
  _min: CrmPipelineStageMinAggregateOutputType | null
  _max: CrmPipelineStageMaxAggregateOutputType | null
}

export type GetCrmPipelineStageGroupByPayload<T extends CrmPipelineStageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CrmPipelineStageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CrmPipelineStageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CrmPipelineStageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CrmPipelineStageGroupByOutputType[P]>
      }
    >
  >



export type CrmPipelineStageWhereInput = {
  AND?: Prisma.CrmPipelineStageWhereInput | Prisma.CrmPipelineStageWhereInput[]
  OR?: Prisma.CrmPipelineStageWhereInput[]
  NOT?: Prisma.CrmPipelineStageWhereInput | Prisma.CrmPipelineStageWhereInput[]
  id?: Prisma.StringFilter<"CrmPipelineStage"> | string
  pipelineId?: Prisma.StringFilter<"CrmPipelineStage"> | string
  name?: Prisma.StringFilter<"CrmPipelineStage"> | string
  order?: Prisma.IntFilter<"CrmPipelineStage"> | number
  color?: Prisma.StringNullableFilter<"CrmPipelineStage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
  pipeline?: Prisma.XOR<Prisma.CrmPipelineScalarRelationFilter, Prisma.CrmPipelineWhereInput>
  deals?: Prisma.CrmDealListRelationFilter
}

export type CrmPipelineStageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pipelineId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  pipeline?: Prisma.CrmPipelineOrderByWithRelationInput
  deals?: Prisma.CrmDealOrderByRelationAggregateInput
}

export type CrmPipelineStageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CrmPipelineStageWhereInput | Prisma.CrmPipelineStageWhereInput[]
  OR?: Prisma.CrmPipelineStageWhereInput[]
  NOT?: Prisma.CrmPipelineStageWhereInput | Prisma.CrmPipelineStageWhereInput[]
  pipelineId?: Prisma.StringFilter<"CrmPipelineStage"> | string
  name?: Prisma.StringFilter<"CrmPipelineStage"> | string
  order?: Prisma.IntFilter<"CrmPipelineStage"> | number
  color?: Prisma.StringNullableFilter<"CrmPipelineStage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
  pipeline?: Prisma.XOR<Prisma.CrmPipelineScalarRelationFilter, Prisma.CrmPipelineWhereInput>
  deals?: Prisma.CrmDealListRelationFilter
}, "id">

export type CrmPipelineStageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pipelineId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  color?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CrmPipelineStageCountOrderByAggregateInput
  _avg?: Prisma.CrmPipelineStageAvgOrderByAggregateInput
  _max?: Prisma.CrmPipelineStageMaxOrderByAggregateInput
  _min?: Prisma.CrmPipelineStageMinOrderByAggregateInput
  _sum?: Prisma.CrmPipelineStageSumOrderByAggregateInput
}

export type CrmPipelineStageScalarWhereWithAggregatesInput = {
  AND?: Prisma.CrmPipelineStageScalarWhereWithAggregatesInput | Prisma.CrmPipelineStageScalarWhereWithAggregatesInput[]
  OR?: Prisma.CrmPipelineStageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CrmPipelineStageScalarWhereWithAggregatesInput | Prisma.CrmPipelineStageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CrmPipelineStage"> | string
  pipelineId?: Prisma.StringWithAggregatesFilter<"CrmPipelineStage"> | string
  name?: Prisma.StringWithAggregatesFilter<"CrmPipelineStage"> | string
  order?: Prisma.IntWithAggregatesFilter<"CrmPipelineStage"> | number
  color?: Prisma.StringNullableWithAggregatesFilter<"CrmPipelineStage"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CrmPipelineStage"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CrmPipelineStage"> | Date | string
}

export type CrmPipelineStageCreateInput = {
  id?: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pipeline: Prisma.CrmPipelineCreateNestedOneWithoutStagesInput
  deals?: Prisma.CrmDealCreateNestedManyWithoutStageInput
}

export type CrmPipelineStageUncheckedCreateInput = {
  id?: string
  pipelineId: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deals?: Prisma.CrmDealUncheckedCreateNestedManyWithoutStageInput
}

export type CrmPipelineStageUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pipeline?: Prisma.CrmPipelineUpdateOneRequiredWithoutStagesNestedInput
  deals?: Prisma.CrmDealUpdateManyWithoutStageNestedInput
}

export type CrmPipelineStageUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pipelineId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.CrmDealUncheckedUpdateManyWithoutStageNestedInput
}

export type CrmPipelineStageCreateManyInput = {
  id?: string
  pipelineId: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmPipelineStageUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmPipelineStageUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pipelineId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmPipelineStageListRelationFilter = {
  every?: Prisma.CrmPipelineStageWhereInput
  some?: Prisma.CrmPipelineStageWhereInput
  none?: Prisma.CrmPipelineStageWhereInput
}

export type CrmPipelineStageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CrmPipelineStageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pipelineId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  color?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmPipelineStageAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CrmPipelineStageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pipelineId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  color?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmPipelineStageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pipelineId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  order?: Prisma.SortOrder
  color?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CrmPipelineStageSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CrmPipelineStageScalarRelationFilter = {
  is?: Prisma.CrmPipelineStageWhereInput
  isNot?: Prisma.CrmPipelineStageWhereInput
}

export type CrmPipelineStageCreateNestedManyWithoutPipelineInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput> | Prisma.CrmPipelineStageCreateWithoutPipelineInput[] | Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput[]
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput | Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput[]
  createMany?: Prisma.CrmPipelineStageCreateManyPipelineInputEnvelope
  connect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
}

export type CrmPipelineStageUncheckedCreateNestedManyWithoutPipelineInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput> | Prisma.CrmPipelineStageCreateWithoutPipelineInput[] | Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput[]
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput | Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput[]
  createMany?: Prisma.CrmPipelineStageCreateManyPipelineInputEnvelope
  connect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
}

export type CrmPipelineStageUpdateManyWithoutPipelineNestedInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput> | Prisma.CrmPipelineStageCreateWithoutPipelineInput[] | Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput[]
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput | Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput[]
  upsert?: Prisma.CrmPipelineStageUpsertWithWhereUniqueWithoutPipelineInput | Prisma.CrmPipelineStageUpsertWithWhereUniqueWithoutPipelineInput[]
  createMany?: Prisma.CrmPipelineStageCreateManyPipelineInputEnvelope
  set?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  disconnect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  delete?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  connect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  update?: Prisma.CrmPipelineStageUpdateWithWhereUniqueWithoutPipelineInput | Prisma.CrmPipelineStageUpdateWithWhereUniqueWithoutPipelineInput[]
  updateMany?: Prisma.CrmPipelineStageUpdateManyWithWhereWithoutPipelineInput | Prisma.CrmPipelineStageUpdateManyWithWhereWithoutPipelineInput[]
  deleteMany?: Prisma.CrmPipelineStageScalarWhereInput | Prisma.CrmPipelineStageScalarWhereInput[]
}

export type CrmPipelineStageUncheckedUpdateManyWithoutPipelineNestedInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput> | Prisma.CrmPipelineStageCreateWithoutPipelineInput[] | Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput[]
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput | Prisma.CrmPipelineStageCreateOrConnectWithoutPipelineInput[]
  upsert?: Prisma.CrmPipelineStageUpsertWithWhereUniqueWithoutPipelineInput | Prisma.CrmPipelineStageUpsertWithWhereUniqueWithoutPipelineInput[]
  createMany?: Prisma.CrmPipelineStageCreateManyPipelineInputEnvelope
  set?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  disconnect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  delete?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  connect?: Prisma.CrmPipelineStageWhereUniqueInput | Prisma.CrmPipelineStageWhereUniqueInput[]
  update?: Prisma.CrmPipelineStageUpdateWithWhereUniqueWithoutPipelineInput | Prisma.CrmPipelineStageUpdateWithWhereUniqueWithoutPipelineInput[]
  updateMany?: Prisma.CrmPipelineStageUpdateManyWithWhereWithoutPipelineInput | Prisma.CrmPipelineStageUpdateManyWithWhereWithoutPipelineInput[]
  deleteMany?: Prisma.CrmPipelineStageScalarWhereInput | Prisma.CrmPipelineStageScalarWhereInput[]
}

export type CrmPipelineStageCreateNestedOneWithoutDealsInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedCreateWithoutDealsInput>
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutDealsInput
  connect?: Prisma.CrmPipelineStageWhereUniqueInput
}

export type CrmPipelineStageUpdateOneRequiredWithoutDealsNestedInput = {
  create?: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedCreateWithoutDealsInput>
  connectOrCreate?: Prisma.CrmPipelineStageCreateOrConnectWithoutDealsInput
  upsert?: Prisma.CrmPipelineStageUpsertWithoutDealsInput
  connect?: Prisma.CrmPipelineStageWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.CrmPipelineStageUpdateToOneWithWhereWithoutDealsInput, Prisma.CrmPipelineStageUpdateWithoutDealsInput>, Prisma.CrmPipelineStageUncheckedUpdateWithoutDealsInput>
}

export type CrmPipelineStageCreateWithoutPipelineInput = {
  id?: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deals?: Prisma.CrmDealCreateNestedManyWithoutStageInput
}

export type CrmPipelineStageUncheckedCreateWithoutPipelineInput = {
  id?: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deals?: Prisma.CrmDealUncheckedCreateNestedManyWithoutStageInput
}

export type CrmPipelineStageCreateOrConnectWithoutPipelineInput = {
  where: Prisma.CrmPipelineStageWhereUniqueInput
  create: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput>
}

export type CrmPipelineStageCreateManyPipelineInputEnvelope = {
  data: Prisma.CrmPipelineStageCreateManyPipelineInput | Prisma.CrmPipelineStageCreateManyPipelineInput[]
  skipDuplicates?: boolean
}

export type CrmPipelineStageUpsertWithWhereUniqueWithoutPipelineInput = {
  where: Prisma.CrmPipelineStageWhereUniqueInput
  update: Prisma.XOR<Prisma.CrmPipelineStageUpdateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedUpdateWithoutPipelineInput>
  create: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedCreateWithoutPipelineInput>
}

export type CrmPipelineStageUpdateWithWhereUniqueWithoutPipelineInput = {
  where: Prisma.CrmPipelineStageWhereUniqueInput
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateWithoutPipelineInput, Prisma.CrmPipelineStageUncheckedUpdateWithoutPipelineInput>
}

export type CrmPipelineStageUpdateManyWithWhereWithoutPipelineInput = {
  where: Prisma.CrmPipelineStageScalarWhereInput
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateManyMutationInput, Prisma.CrmPipelineStageUncheckedUpdateManyWithoutPipelineInput>
}

export type CrmPipelineStageScalarWhereInput = {
  AND?: Prisma.CrmPipelineStageScalarWhereInput | Prisma.CrmPipelineStageScalarWhereInput[]
  OR?: Prisma.CrmPipelineStageScalarWhereInput[]
  NOT?: Prisma.CrmPipelineStageScalarWhereInput | Prisma.CrmPipelineStageScalarWhereInput[]
  id?: Prisma.StringFilter<"CrmPipelineStage"> | string
  pipelineId?: Prisma.StringFilter<"CrmPipelineStage"> | string
  name?: Prisma.StringFilter<"CrmPipelineStage"> | string
  order?: Prisma.IntFilter<"CrmPipelineStage"> | number
  color?: Prisma.StringNullableFilter<"CrmPipelineStage"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CrmPipelineStage"> | Date | string
}

export type CrmPipelineStageCreateWithoutDealsInput = {
  id?: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  pipeline: Prisma.CrmPipelineCreateNestedOneWithoutStagesInput
}

export type CrmPipelineStageUncheckedCreateWithoutDealsInput = {
  id?: string
  pipelineId: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmPipelineStageCreateOrConnectWithoutDealsInput = {
  where: Prisma.CrmPipelineStageWhereUniqueInput
  create: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedCreateWithoutDealsInput>
}

export type CrmPipelineStageUpsertWithoutDealsInput = {
  update: Prisma.XOR<Prisma.CrmPipelineStageUpdateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedUpdateWithoutDealsInput>
  create: Prisma.XOR<Prisma.CrmPipelineStageCreateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedCreateWithoutDealsInput>
  where?: Prisma.CrmPipelineStageWhereInput
}

export type CrmPipelineStageUpdateToOneWithWhereWithoutDealsInput = {
  where?: Prisma.CrmPipelineStageWhereInput
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateWithoutDealsInput, Prisma.CrmPipelineStageUncheckedUpdateWithoutDealsInput>
}

export type CrmPipelineStageUpdateWithoutDealsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pipeline?: Prisma.CrmPipelineUpdateOneRequiredWithoutStagesNestedInput
}

export type CrmPipelineStageUncheckedUpdateWithoutDealsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pipelineId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CrmPipelineStageCreateManyPipelineInput = {
  id?: string
  name: string
  order: number
  color?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CrmPipelineStageUpdateWithoutPipelineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.CrmDealUpdateManyWithoutStageNestedInput
}

export type CrmPipelineStageUncheckedUpdateWithoutPipelineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.CrmDealUncheckedUpdateManyWithoutStageNestedInput
}

export type CrmPipelineStageUncheckedUpdateManyWithoutPipelineInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  color?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type CrmPipelineStageCountOutputType
 */

export type CrmPipelineStageCountOutputType = {
  deals: number
}

export type CrmPipelineStageCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  deals?: boolean | CrmPipelineStageCountOutputTypeCountDealsArgs
}

/**
 * CrmPipelineStageCountOutputType without action
 */
export type CrmPipelineStageCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStageCountOutputType
   */
  select?: Prisma.CrmPipelineStageCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CrmPipelineStageCountOutputType without action
 */
export type CrmPipelineStageCountOutputTypeCountDealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CrmDealWhereInput
}


export type CrmPipelineStageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pipelineId?: boolean
  name?: boolean
  order?: boolean
  color?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
  deals?: boolean | Prisma.CrmPipelineStage$dealsArgs<ExtArgs>
  _count?: boolean | Prisma.CrmPipelineStageCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmPipelineStage"]>

export type CrmPipelineStageSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pipelineId?: boolean
  name?: boolean
  order?: boolean
  color?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmPipelineStage"]>

export type CrmPipelineStageSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pipelineId?: boolean
  name?: boolean
  order?: boolean
  color?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
}, ExtArgs["result"]["crmPipelineStage"]>

export type CrmPipelineStageSelectScalar = {
  id?: boolean
  pipelineId?: boolean
  name?: boolean
  order?: boolean
  color?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CrmPipelineStageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pipelineId" | "name" | "order" | "color" | "createdAt" | "updatedAt", ExtArgs["result"]["crmPipelineStage"]>
export type CrmPipelineStageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
  deals?: boolean | Prisma.CrmPipelineStage$dealsArgs<ExtArgs>
  _count?: boolean | Prisma.CrmPipelineStageCountOutputTypeDefaultArgs<ExtArgs>
}
export type CrmPipelineStageIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
}
export type CrmPipelineStageIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pipeline?: boolean | Prisma.CrmPipelineDefaultArgs<ExtArgs>
}

export type $CrmPipelineStagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CrmPipelineStage"
  objects: {
    pipeline: Prisma.$CrmPipelinePayload<ExtArgs>
    deals: Prisma.$CrmDealPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pipelineId: string
    name: string
    order: number
    color: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["crmPipelineStage"]>
  composites: {}
}

export type CrmPipelineStageGetPayload<S extends boolean | null | undefined | CrmPipelineStageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload, S>

export type CrmPipelineStageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CrmPipelineStageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CrmPipelineStageCountAggregateInputType | true
  }

export interface CrmPipelineStageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CrmPipelineStage'], meta: { name: 'CrmPipelineStage' } }
  /**
   * Find zero or one CrmPipelineStage that matches the filter.
   * @param {CrmPipelineStageFindUniqueArgs} args - Arguments to find a CrmPipelineStage
   * @example
   * // Get one CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CrmPipelineStageFindUniqueArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CrmPipelineStage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CrmPipelineStageFindUniqueOrThrowArgs} args - Arguments to find a CrmPipelineStage
   * @example
   * // Get one CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CrmPipelineStageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CrmPipelineStage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageFindFirstArgs} args - Arguments to find a CrmPipelineStage
   * @example
   * // Get one CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CrmPipelineStageFindFirstArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageFindFirstArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CrmPipelineStage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageFindFirstOrThrowArgs} args - Arguments to find a CrmPipelineStage
   * @example
   * // Get one CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CrmPipelineStageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CrmPipelineStages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CrmPipelineStages
   * const crmPipelineStages = await prisma.crmPipelineStage.findMany()
   * 
   * // Get first 10 CrmPipelineStages
   * const crmPipelineStages = await prisma.crmPipelineStage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const crmPipelineStageWithIdOnly = await prisma.crmPipelineStage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CrmPipelineStageFindManyArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CrmPipelineStage.
   * @param {CrmPipelineStageCreateArgs} args - Arguments to create a CrmPipelineStage.
   * @example
   * // Create one CrmPipelineStage
   * const CrmPipelineStage = await prisma.crmPipelineStage.create({
   *   data: {
   *     // ... data to create a CrmPipelineStage
   *   }
   * })
   * 
   */
  create<T extends CrmPipelineStageCreateArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageCreateArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CrmPipelineStages.
   * @param {CrmPipelineStageCreateManyArgs} args - Arguments to create many CrmPipelineStages.
   * @example
   * // Create many CrmPipelineStages
   * const crmPipelineStage = await prisma.crmPipelineStage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CrmPipelineStageCreateManyArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CrmPipelineStages and returns the data saved in the database.
   * @param {CrmPipelineStageCreateManyAndReturnArgs} args - Arguments to create many CrmPipelineStages.
   * @example
   * // Create many CrmPipelineStages
   * const crmPipelineStage = await prisma.crmPipelineStage.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CrmPipelineStages and only return the `id`
   * const crmPipelineStageWithIdOnly = await prisma.crmPipelineStage.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CrmPipelineStageCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CrmPipelineStage.
   * @param {CrmPipelineStageDeleteArgs} args - Arguments to delete one CrmPipelineStage.
   * @example
   * // Delete one CrmPipelineStage
   * const CrmPipelineStage = await prisma.crmPipelineStage.delete({
   *   where: {
   *     // ... filter to delete one CrmPipelineStage
   *   }
   * })
   * 
   */
  delete<T extends CrmPipelineStageDeleteArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageDeleteArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CrmPipelineStage.
   * @param {CrmPipelineStageUpdateArgs} args - Arguments to update one CrmPipelineStage.
   * @example
   * // Update one CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CrmPipelineStageUpdateArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageUpdateArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CrmPipelineStages.
   * @param {CrmPipelineStageDeleteManyArgs} args - Arguments to filter CrmPipelineStages to delete.
   * @example
   * // Delete a few CrmPipelineStages
   * const { count } = await prisma.crmPipelineStage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CrmPipelineStageDeleteManyArgs>(args?: Prisma.SelectSubset<T, CrmPipelineStageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CrmPipelineStages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CrmPipelineStages
   * const crmPipelineStage = await prisma.crmPipelineStage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CrmPipelineStageUpdateManyArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CrmPipelineStages and returns the data updated in the database.
   * @param {CrmPipelineStageUpdateManyAndReturnArgs} args - Arguments to update many CrmPipelineStages.
   * @example
   * // Update many CrmPipelineStages
   * const crmPipelineStage = await prisma.crmPipelineStage.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CrmPipelineStages and only return the `id`
   * const crmPipelineStageWithIdOnly = await prisma.crmPipelineStage.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CrmPipelineStageUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CrmPipelineStage.
   * @param {CrmPipelineStageUpsertArgs} args - Arguments to update or create a CrmPipelineStage.
   * @example
   * // Update or create a CrmPipelineStage
   * const crmPipelineStage = await prisma.crmPipelineStage.upsert({
   *   create: {
   *     // ... data to create a CrmPipelineStage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CrmPipelineStage we want to update
   *   }
   * })
   */
  upsert<T extends CrmPipelineStageUpsertArgs>(args: Prisma.SelectSubset<T, CrmPipelineStageUpsertArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineStageClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelineStagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CrmPipelineStages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageCountArgs} args - Arguments to filter CrmPipelineStages to count.
   * @example
   * // Count the number of CrmPipelineStages
   * const count = await prisma.crmPipelineStage.count({
   *   where: {
   *     // ... the filter for the CrmPipelineStages we want to count
   *   }
   * })
  **/
  count<T extends CrmPipelineStageCountArgs>(
    args?: Prisma.Subset<T, CrmPipelineStageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CrmPipelineStageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CrmPipelineStage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CrmPipelineStageAggregateArgs>(args: Prisma.Subset<T, CrmPipelineStageAggregateArgs>): Prisma.PrismaPromise<GetCrmPipelineStageAggregateType<T>>

  /**
   * Group by CrmPipelineStage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CrmPipelineStageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CrmPipelineStageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CrmPipelineStageGroupByArgs['orderBy'] }
      : { orderBy?: CrmPipelineStageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CrmPipelineStageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCrmPipelineStageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CrmPipelineStage model
 */
readonly fields: CrmPipelineStageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CrmPipelineStage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CrmPipelineStageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pipeline<T extends Prisma.CrmPipelineDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CrmPipelineDefaultArgs<ExtArgs>>): Prisma.Prisma__CrmPipelineClient<runtime.Types.Result.GetResult<Prisma.$CrmPipelinePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  deals<T extends Prisma.CrmPipelineStage$dealsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CrmPipelineStage$dealsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CrmDealPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CrmPipelineStage model
 */
export interface CrmPipelineStageFieldRefs {
  readonly id: Prisma.FieldRef<"CrmPipelineStage", 'String'>
  readonly pipelineId: Prisma.FieldRef<"CrmPipelineStage", 'String'>
  readonly name: Prisma.FieldRef<"CrmPipelineStage", 'String'>
  readonly order: Prisma.FieldRef<"CrmPipelineStage", 'Int'>
  readonly color: Prisma.FieldRef<"CrmPipelineStage", 'String'>
  readonly createdAt: Prisma.FieldRef<"CrmPipelineStage", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CrmPipelineStage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CrmPipelineStage findUnique
 */
export type CrmPipelineStageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter, which CrmPipelineStage to fetch.
   */
  where: Prisma.CrmPipelineStageWhereUniqueInput
}

/**
 * CrmPipelineStage findUniqueOrThrow
 */
export type CrmPipelineStageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter, which CrmPipelineStage to fetch.
   */
  where: Prisma.CrmPipelineStageWhereUniqueInput
}

/**
 * CrmPipelineStage findFirst
 */
export type CrmPipelineStageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter, which CrmPipelineStage to fetch.
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmPipelineStages to fetch.
   */
  orderBy?: Prisma.CrmPipelineStageOrderByWithRelationInput | Prisma.CrmPipelineStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CrmPipelineStages.
   */
  cursor?: Prisma.CrmPipelineStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmPipelineStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmPipelineStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CrmPipelineStages.
   */
  distinct?: Prisma.CrmPipelineStageScalarFieldEnum | Prisma.CrmPipelineStageScalarFieldEnum[]
}

/**
 * CrmPipelineStage findFirstOrThrow
 */
export type CrmPipelineStageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter, which CrmPipelineStage to fetch.
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmPipelineStages to fetch.
   */
  orderBy?: Prisma.CrmPipelineStageOrderByWithRelationInput | Prisma.CrmPipelineStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CrmPipelineStages.
   */
  cursor?: Prisma.CrmPipelineStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmPipelineStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmPipelineStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CrmPipelineStages.
   */
  distinct?: Prisma.CrmPipelineStageScalarFieldEnum | Prisma.CrmPipelineStageScalarFieldEnum[]
}

/**
 * CrmPipelineStage findMany
 */
export type CrmPipelineStageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter, which CrmPipelineStages to fetch.
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CrmPipelineStages to fetch.
   */
  orderBy?: Prisma.CrmPipelineStageOrderByWithRelationInput | Prisma.CrmPipelineStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CrmPipelineStages.
   */
  cursor?: Prisma.CrmPipelineStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CrmPipelineStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CrmPipelineStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CrmPipelineStages.
   */
  distinct?: Prisma.CrmPipelineStageScalarFieldEnum | Prisma.CrmPipelineStageScalarFieldEnum[]
}

/**
 * CrmPipelineStage create
 */
export type CrmPipelineStageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * The data needed to create a CrmPipelineStage.
   */
  data: Prisma.XOR<Prisma.CrmPipelineStageCreateInput, Prisma.CrmPipelineStageUncheckedCreateInput>
}

/**
 * CrmPipelineStage createMany
 */
export type CrmPipelineStageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CrmPipelineStages.
   */
  data: Prisma.CrmPipelineStageCreateManyInput | Prisma.CrmPipelineStageCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CrmPipelineStage createManyAndReturn
 */
export type CrmPipelineStageCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * The data used to create many CrmPipelineStages.
   */
  data: Prisma.CrmPipelineStageCreateManyInput | Prisma.CrmPipelineStageCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CrmPipelineStage update
 */
export type CrmPipelineStageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * The data needed to update a CrmPipelineStage.
   */
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateInput, Prisma.CrmPipelineStageUncheckedUpdateInput>
  /**
   * Choose, which CrmPipelineStage to update.
   */
  where: Prisma.CrmPipelineStageWhereUniqueInput
}

/**
 * CrmPipelineStage updateMany
 */
export type CrmPipelineStageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CrmPipelineStages.
   */
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateManyMutationInput, Prisma.CrmPipelineStageUncheckedUpdateManyInput>
  /**
   * Filter which CrmPipelineStages to update
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * Limit how many CrmPipelineStages to update.
   */
  limit?: number
}

/**
 * CrmPipelineStage updateManyAndReturn
 */
export type CrmPipelineStageUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * The data used to update CrmPipelineStages.
   */
  data: Prisma.XOR<Prisma.CrmPipelineStageUpdateManyMutationInput, Prisma.CrmPipelineStageUncheckedUpdateManyInput>
  /**
   * Filter which CrmPipelineStages to update
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * Limit how many CrmPipelineStages to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CrmPipelineStage upsert
 */
export type CrmPipelineStageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * The filter to search for the CrmPipelineStage to update in case it exists.
   */
  where: Prisma.CrmPipelineStageWhereUniqueInput
  /**
   * In case the CrmPipelineStage found by the `where` argument doesn't exist, create a new CrmPipelineStage with this data.
   */
  create: Prisma.XOR<Prisma.CrmPipelineStageCreateInput, Prisma.CrmPipelineStageUncheckedCreateInput>
  /**
   * In case the CrmPipelineStage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CrmPipelineStageUpdateInput, Prisma.CrmPipelineStageUncheckedUpdateInput>
}

/**
 * CrmPipelineStage delete
 */
export type CrmPipelineStageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
  /**
   * Filter which CrmPipelineStage to delete.
   */
  where: Prisma.CrmPipelineStageWhereUniqueInput
}

/**
 * CrmPipelineStage deleteMany
 */
export type CrmPipelineStageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CrmPipelineStages to delete
   */
  where?: Prisma.CrmPipelineStageWhereInput
  /**
   * Limit how many CrmPipelineStages to delete.
   */
  limit?: number
}

/**
 * CrmPipelineStage.deals
 */
export type CrmPipelineStage$dealsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmDeal
   */
  select?: Prisma.CrmDealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmDeal
   */
  omit?: Prisma.CrmDealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmDealInclude<ExtArgs> | null
  where?: Prisma.CrmDealWhereInput
  orderBy?: Prisma.CrmDealOrderByWithRelationInput | Prisma.CrmDealOrderByWithRelationInput[]
  cursor?: Prisma.CrmDealWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CrmDealScalarFieldEnum | Prisma.CrmDealScalarFieldEnum[]
}

/**
 * CrmPipelineStage without action
 */
export type CrmPipelineStageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CrmPipelineStage
   */
  select?: Prisma.CrmPipelineStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CrmPipelineStage
   */
  omit?: Prisma.CrmPipelineStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CrmPipelineStageInclude<ExtArgs> | null
}
