
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MealOptionCatalog` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model MealOptionCatalog
 * 
 */
export type MealOptionCatalogModel = runtime.Types.Result.DefaultSelection<Prisma.$MealOptionCatalogPayload>

export type AggregateMealOptionCatalog = {
  _count: MealOptionCatalogCountAggregateOutputType | null
  _avg: MealOptionCatalogAvgAggregateOutputType | null
  _sum: MealOptionCatalogSumAggregateOutputType | null
  _min: MealOptionCatalogMinAggregateOutputType | null
  _max: MealOptionCatalogMaxAggregateOutputType | null
}

export type MealOptionCatalogAvgAggregateOutputType = {
  prepMinutes: number | null
}

export type MealOptionCatalogSumAggregateOutputType = {
  prepMinutes: number | null
}

export type MealOptionCatalogMinAggregateOutputType = {
  id: string | null
  title: string | null
  windowType: string | null
  absorptionType: string | null
  keyIngredient: string | null
  prepMinutes: number | null
  source: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MealOptionCatalogMaxAggregateOutputType = {
  id: string | null
  title: string | null
  windowType: string | null
  absorptionType: string | null
  keyIngredient: string | null
  prepMinutes: number | null
  source: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MealOptionCatalogCountAggregateOutputType = {
  id: number
  title: number
  windowType: number
  absorptionType: number
  dietaryBuckets: number
  baseMacros: number
  keyIngredient: number
  ingredients: number
  prepMinutes: number
  constraintTags: number
  source: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MealOptionCatalogAvgAggregateInputType = {
  prepMinutes?: true
}

export type MealOptionCatalogSumAggregateInputType = {
  prepMinutes?: true
}

export type MealOptionCatalogMinAggregateInputType = {
  id?: true
  title?: true
  windowType?: true
  absorptionType?: true
  keyIngredient?: true
  prepMinutes?: true
  source?: true
  createdAt?: true
  updatedAt?: true
}

export type MealOptionCatalogMaxAggregateInputType = {
  id?: true
  title?: true
  windowType?: true
  absorptionType?: true
  keyIngredient?: true
  prepMinutes?: true
  source?: true
  createdAt?: true
  updatedAt?: true
}

export type MealOptionCatalogCountAggregateInputType = {
  id?: true
  title?: true
  windowType?: true
  absorptionType?: true
  dietaryBuckets?: true
  baseMacros?: true
  keyIngredient?: true
  ingredients?: true
  prepMinutes?: true
  constraintTags?: true
  source?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MealOptionCatalogAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MealOptionCatalog to aggregate.
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MealOptionCatalogs to fetch.
   */
  orderBy?: Prisma.MealOptionCatalogOrderByWithRelationInput | Prisma.MealOptionCatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MealOptionCatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MealOptionCatalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MealOptionCatalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MealOptionCatalogs
  **/
  _count?: true | MealOptionCatalogCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MealOptionCatalogAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MealOptionCatalogSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MealOptionCatalogMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MealOptionCatalogMaxAggregateInputType
}

export type GetMealOptionCatalogAggregateType<T extends MealOptionCatalogAggregateArgs> = {
      [P in keyof T & keyof AggregateMealOptionCatalog]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMealOptionCatalog[P]>
    : Prisma.GetScalarType<T[P], AggregateMealOptionCatalog[P]>
}




export type MealOptionCatalogGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MealOptionCatalogWhereInput
  orderBy?: Prisma.MealOptionCatalogOrderByWithAggregationInput | Prisma.MealOptionCatalogOrderByWithAggregationInput[]
  by: Prisma.MealOptionCatalogScalarFieldEnum[] | Prisma.MealOptionCatalogScalarFieldEnum
  having?: Prisma.MealOptionCatalogScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MealOptionCatalogCountAggregateInputType | true
  _avg?: MealOptionCatalogAvgAggregateInputType
  _sum?: MealOptionCatalogSumAggregateInputType
  _min?: MealOptionCatalogMinAggregateInputType
  _max?: MealOptionCatalogMaxAggregateInputType
}

export type MealOptionCatalogGroupByOutputType = {
  id: string
  title: string
  windowType: string
  absorptionType: string
  dietaryBuckets: string[]
  baseMacros: runtime.JsonValue
  keyIngredient: string
  ingredients: runtime.JsonValue
  prepMinutes: number
  constraintTags: string[]
  source: string
  createdAt: Date
  updatedAt: Date
  _count: MealOptionCatalogCountAggregateOutputType | null
  _avg: MealOptionCatalogAvgAggregateOutputType | null
  _sum: MealOptionCatalogSumAggregateOutputType | null
  _min: MealOptionCatalogMinAggregateOutputType | null
  _max: MealOptionCatalogMaxAggregateOutputType | null
}

export type GetMealOptionCatalogGroupByPayload<T extends MealOptionCatalogGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MealOptionCatalogGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MealOptionCatalogGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MealOptionCatalogGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MealOptionCatalogGroupByOutputType[P]>
      }
    >
  >



export type MealOptionCatalogWhereInput = {
  AND?: Prisma.MealOptionCatalogWhereInput | Prisma.MealOptionCatalogWhereInput[]
  OR?: Prisma.MealOptionCatalogWhereInput[]
  NOT?: Prisma.MealOptionCatalogWhereInput | Prisma.MealOptionCatalogWhereInput[]
  id?: Prisma.StringFilter<"MealOptionCatalog"> | string
  title?: Prisma.StringFilter<"MealOptionCatalog"> | string
  windowType?: Prisma.StringFilter<"MealOptionCatalog"> | string
  absorptionType?: Prisma.StringFilter<"MealOptionCatalog"> | string
  dietaryBuckets?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  baseMacros?: Prisma.JsonFilter<"MealOptionCatalog">
  keyIngredient?: Prisma.StringFilter<"MealOptionCatalog"> | string
  ingredients?: Prisma.JsonFilter<"MealOptionCatalog">
  prepMinutes?: Prisma.IntFilter<"MealOptionCatalog"> | number
  constraintTags?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  source?: Prisma.StringFilter<"MealOptionCatalog"> | string
  createdAt?: Prisma.DateTimeFilter<"MealOptionCatalog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MealOptionCatalog"> | Date | string
}

export type MealOptionCatalogOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  windowType?: Prisma.SortOrder
  absorptionType?: Prisma.SortOrder
  dietaryBuckets?: Prisma.SortOrder
  baseMacros?: Prisma.SortOrder
  keyIngredient?: Prisma.SortOrder
  ingredients?: Prisma.SortOrder
  prepMinutes?: Prisma.SortOrder
  constraintTags?: Prisma.SortOrder
  source?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MealOptionCatalogWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MealOptionCatalogWhereInput | Prisma.MealOptionCatalogWhereInput[]
  OR?: Prisma.MealOptionCatalogWhereInput[]
  NOT?: Prisma.MealOptionCatalogWhereInput | Prisma.MealOptionCatalogWhereInput[]
  title?: Prisma.StringFilter<"MealOptionCatalog"> | string
  windowType?: Prisma.StringFilter<"MealOptionCatalog"> | string
  absorptionType?: Prisma.StringFilter<"MealOptionCatalog"> | string
  dietaryBuckets?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  baseMacros?: Prisma.JsonFilter<"MealOptionCatalog">
  keyIngredient?: Prisma.StringFilter<"MealOptionCatalog"> | string
  ingredients?: Prisma.JsonFilter<"MealOptionCatalog">
  prepMinutes?: Prisma.IntFilter<"MealOptionCatalog"> | number
  constraintTags?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  source?: Prisma.StringFilter<"MealOptionCatalog"> | string
  createdAt?: Prisma.DateTimeFilter<"MealOptionCatalog"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MealOptionCatalog"> | Date | string
}, "id">

export type MealOptionCatalogOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  windowType?: Prisma.SortOrder
  absorptionType?: Prisma.SortOrder
  dietaryBuckets?: Prisma.SortOrder
  baseMacros?: Prisma.SortOrder
  keyIngredient?: Prisma.SortOrder
  ingredients?: Prisma.SortOrder
  prepMinutes?: Prisma.SortOrder
  constraintTags?: Prisma.SortOrder
  source?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MealOptionCatalogCountOrderByAggregateInput
  _avg?: Prisma.MealOptionCatalogAvgOrderByAggregateInput
  _max?: Prisma.MealOptionCatalogMaxOrderByAggregateInput
  _min?: Prisma.MealOptionCatalogMinOrderByAggregateInput
  _sum?: Prisma.MealOptionCatalogSumOrderByAggregateInput
}

export type MealOptionCatalogScalarWhereWithAggregatesInput = {
  AND?: Prisma.MealOptionCatalogScalarWhereWithAggregatesInput | Prisma.MealOptionCatalogScalarWhereWithAggregatesInput[]
  OR?: Prisma.MealOptionCatalogScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MealOptionCatalogScalarWhereWithAggregatesInput | Prisma.MealOptionCatalogScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  title?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  windowType?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  absorptionType?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  dietaryBuckets?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  baseMacros?: Prisma.JsonWithAggregatesFilter<"MealOptionCatalog">
  keyIngredient?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  ingredients?: Prisma.JsonWithAggregatesFilter<"MealOptionCatalog">
  prepMinutes?: Prisma.IntWithAggregatesFilter<"MealOptionCatalog"> | number
  constraintTags?: Prisma.StringNullableListFilter<"MealOptionCatalog">
  source?: Prisma.StringWithAggregatesFilter<"MealOptionCatalog"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MealOptionCatalog"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MealOptionCatalog"> | Date | string
}

export type MealOptionCatalogCreateInput = {
  id?: string
  title: string
  windowType: string
  absorptionType: string
  dietaryBuckets?: Prisma.MealOptionCatalogCreatedietaryBucketsInput | string[]
  baseMacros: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient: string
  ingredients: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes: number
  constraintTags?: Prisma.MealOptionCatalogCreateconstraintTagsInput | string[]
  source?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MealOptionCatalogUncheckedCreateInput = {
  id?: string
  title: string
  windowType: string
  absorptionType: string
  dietaryBuckets?: Prisma.MealOptionCatalogCreatedietaryBucketsInput | string[]
  baseMacros: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient: string
  ingredients: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes: number
  constraintTags?: Prisma.MealOptionCatalogCreateconstraintTagsInput | string[]
  source?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MealOptionCatalogUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  windowType?: Prisma.StringFieldUpdateOperationsInput | string
  absorptionType?: Prisma.StringFieldUpdateOperationsInput | string
  dietaryBuckets?: Prisma.MealOptionCatalogUpdatedietaryBucketsInput | string[]
  baseMacros?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient?: Prisma.StringFieldUpdateOperationsInput | string
  ingredients?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  constraintTags?: Prisma.MealOptionCatalogUpdateconstraintTagsInput | string[]
  source?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MealOptionCatalogUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  windowType?: Prisma.StringFieldUpdateOperationsInput | string
  absorptionType?: Prisma.StringFieldUpdateOperationsInput | string
  dietaryBuckets?: Prisma.MealOptionCatalogUpdatedietaryBucketsInput | string[]
  baseMacros?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient?: Prisma.StringFieldUpdateOperationsInput | string
  ingredients?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  constraintTags?: Prisma.MealOptionCatalogUpdateconstraintTagsInput | string[]
  source?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MealOptionCatalogCreateManyInput = {
  id?: string
  title: string
  windowType: string
  absorptionType: string
  dietaryBuckets?: Prisma.MealOptionCatalogCreatedietaryBucketsInput | string[]
  baseMacros: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient: string
  ingredients: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes: number
  constraintTags?: Prisma.MealOptionCatalogCreateconstraintTagsInput | string[]
  source?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MealOptionCatalogUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  windowType?: Prisma.StringFieldUpdateOperationsInput | string
  absorptionType?: Prisma.StringFieldUpdateOperationsInput | string
  dietaryBuckets?: Prisma.MealOptionCatalogUpdatedietaryBucketsInput | string[]
  baseMacros?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient?: Prisma.StringFieldUpdateOperationsInput | string
  ingredients?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  constraintTags?: Prisma.MealOptionCatalogUpdateconstraintTagsInput | string[]
  source?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MealOptionCatalogUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  windowType?: Prisma.StringFieldUpdateOperationsInput | string
  absorptionType?: Prisma.StringFieldUpdateOperationsInput | string
  dietaryBuckets?: Prisma.MealOptionCatalogUpdatedietaryBucketsInput | string[]
  baseMacros?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  keyIngredient?: Prisma.StringFieldUpdateOperationsInput | string
  ingredients?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  prepMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  constraintTags?: Prisma.MealOptionCatalogUpdateconstraintTagsInput | string[]
  source?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MealOptionCatalogCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  windowType?: Prisma.SortOrder
  absorptionType?: Prisma.SortOrder
  dietaryBuckets?: Prisma.SortOrder
  baseMacros?: Prisma.SortOrder
  keyIngredient?: Prisma.SortOrder
  ingredients?: Prisma.SortOrder
  prepMinutes?: Prisma.SortOrder
  constraintTags?: Prisma.SortOrder
  source?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MealOptionCatalogAvgOrderByAggregateInput = {
  prepMinutes?: Prisma.SortOrder
}

export type MealOptionCatalogMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  windowType?: Prisma.SortOrder
  absorptionType?: Prisma.SortOrder
  keyIngredient?: Prisma.SortOrder
  prepMinutes?: Prisma.SortOrder
  source?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MealOptionCatalogMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  windowType?: Prisma.SortOrder
  absorptionType?: Prisma.SortOrder
  keyIngredient?: Prisma.SortOrder
  prepMinutes?: Prisma.SortOrder
  source?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MealOptionCatalogSumOrderByAggregateInput = {
  prepMinutes?: Prisma.SortOrder
}

export type MealOptionCatalogCreatedietaryBucketsInput = {
  set: string[]
}

export type MealOptionCatalogCreateconstraintTagsInput = {
  set: string[]
}

export type MealOptionCatalogUpdatedietaryBucketsInput = {
  set?: string[]
  push?: string | string[]
}

export type MealOptionCatalogUpdateconstraintTagsInput = {
  set?: string[]
  push?: string | string[]
}



export type MealOptionCatalogSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  windowType?: boolean
  absorptionType?: boolean
  dietaryBuckets?: boolean
  baseMacros?: boolean
  keyIngredient?: boolean
  ingredients?: boolean
  prepMinutes?: boolean
  constraintTags?: boolean
  source?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mealOptionCatalog"]>

export type MealOptionCatalogSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  windowType?: boolean
  absorptionType?: boolean
  dietaryBuckets?: boolean
  baseMacros?: boolean
  keyIngredient?: boolean
  ingredients?: boolean
  prepMinutes?: boolean
  constraintTags?: boolean
  source?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mealOptionCatalog"]>

export type MealOptionCatalogSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  windowType?: boolean
  absorptionType?: boolean
  dietaryBuckets?: boolean
  baseMacros?: boolean
  keyIngredient?: boolean
  ingredients?: boolean
  prepMinutes?: boolean
  constraintTags?: boolean
  source?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["mealOptionCatalog"]>

export type MealOptionCatalogSelectScalar = {
  id?: boolean
  title?: boolean
  windowType?: boolean
  absorptionType?: boolean
  dietaryBuckets?: boolean
  baseMacros?: boolean
  keyIngredient?: boolean
  ingredients?: boolean
  prepMinutes?: boolean
  constraintTags?: boolean
  source?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MealOptionCatalogOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "windowType" | "absorptionType" | "dietaryBuckets" | "baseMacros" | "keyIngredient" | "ingredients" | "prepMinutes" | "constraintTags" | "source" | "createdAt" | "updatedAt", ExtArgs["result"]["mealOptionCatalog"]>

export type $MealOptionCatalogPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MealOptionCatalog"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    windowType: string
    absorptionType: string
    dietaryBuckets: string[]
    baseMacros: runtime.JsonValue
    keyIngredient: string
    ingredients: runtime.JsonValue
    prepMinutes: number
    constraintTags: string[]
    source: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["mealOptionCatalog"]>
  composites: {}
}

export type MealOptionCatalogGetPayload<S extends boolean | null | undefined | MealOptionCatalogDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload, S>

export type MealOptionCatalogCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MealOptionCatalogFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MealOptionCatalogCountAggregateInputType | true
  }

export interface MealOptionCatalogDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MealOptionCatalog'], meta: { name: 'MealOptionCatalog' } }
  /**
   * Find zero or one MealOptionCatalog that matches the filter.
   * @param {MealOptionCatalogFindUniqueArgs} args - Arguments to find a MealOptionCatalog
   * @example
   * // Get one MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MealOptionCatalogFindUniqueArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MealOptionCatalog that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MealOptionCatalogFindUniqueOrThrowArgs} args - Arguments to find a MealOptionCatalog
   * @example
   * // Get one MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MealOptionCatalogFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MealOptionCatalog that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogFindFirstArgs} args - Arguments to find a MealOptionCatalog
   * @example
   * // Get one MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MealOptionCatalogFindFirstArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogFindFirstArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MealOptionCatalog that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogFindFirstOrThrowArgs} args - Arguments to find a MealOptionCatalog
   * @example
   * // Get one MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MealOptionCatalogFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MealOptionCatalogs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MealOptionCatalogs
   * const mealOptionCatalogs = await prisma.mealOptionCatalog.findMany()
   * 
   * // Get first 10 MealOptionCatalogs
   * const mealOptionCatalogs = await prisma.mealOptionCatalog.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const mealOptionCatalogWithIdOnly = await prisma.mealOptionCatalog.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MealOptionCatalogFindManyArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MealOptionCatalog.
   * @param {MealOptionCatalogCreateArgs} args - Arguments to create a MealOptionCatalog.
   * @example
   * // Create one MealOptionCatalog
   * const MealOptionCatalog = await prisma.mealOptionCatalog.create({
   *   data: {
   *     // ... data to create a MealOptionCatalog
   *   }
   * })
   * 
   */
  create<T extends MealOptionCatalogCreateArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogCreateArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MealOptionCatalogs.
   * @param {MealOptionCatalogCreateManyArgs} args - Arguments to create many MealOptionCatalogs.
   * @example
   * // Create many MealOptionCatalogs
   * const mealOptionCatalog = await prisma.mealOptionCatalog.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MealOptionCatalogCreateManyArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MealOptionCatalogs and returns the data saved in the database.
   * @param {MealOptionCatalogCreateManyAndReturnArgs} args - Arguments to create many MealOptionCatalogs.
   * @example
   * // Create many MealOptionCatalogs
   * const mealOptionCatalog = await prisma.mealOptionCatalog.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MealOptionCatalogs and only return the `id`
   * const mealOptionCatalogWithIdOnly = await prisma.mealOptionCatalog.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MealOptionCatalogCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MealOptionCatalog.
   * @param {MealOptionCatalogDeleteArgs} args - Arguments to delete one MealOptionCatalog.
   * @example
   * // Delete one MealOptionCatalog
   * const MealOptionCatalog = await prisma.mealOptionCatalog.delete({
   *   where: {
   *     // ... filter to delete one MealOptionCatalog
   *   }
   * })
   * 
   */
  delete<T extends MealOptionCatalogDeleteArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogDeleteArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MealOptionCatalog.
   * @param {MealOptionCatalogUpdateArgs} args - Arguments to update one MealOptionCatalog.
   * @example
   * // Update one MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MealOptionCatalogUpdateArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogUpdateArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MealOptionCatalogs.
   * @param {MealOptionCatalogDeleteManyArgs} args - Arguments to filter MealOptionCatalogs to delete.
   * @example
   * // Delete a few MealOptionCatalogs
   * const { count } = await prisma.mealOptionCatalog.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MealOptionCatalogDeleteManyArgs>(args?: Prisma.SelectSubset<T, MealOptionCatalogDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MealOptionCatalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MealOptionCatalogs
   * const mealOptionCatalog = await prisma.mealOptionCatalog.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MealOptionCatalogUpdateManyArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MealOptionCatalogs and returns the data updated in the database.
   * @param {MealOptionCatalogUpdateManyAndReturnArgs} args - Arguments to update many MealOptionCatalogs.
   * @example
   * // Update many MealOptionCatalogs
   * const mealOptionCatalog = await prisma.mealOptionCatalog.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MealOptionCatalogs and only return the `id`
   * const mealOptionCatalogWithIdOnly = await prisma.mealOptionCatalog.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MealOptionCatalogUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MealOptionCatalog.
   * @param {MealOptionCatalogUpsertArgs} args - Arguments to update or create a MealOptionCatalog.
   * @example
   * // Update or create a MealOptionCatalog
   * const mealOptionCatalog = await prisma.mealOptionCatalog.upsert({
   *   create: {
   *     // ... data to create a MealOptionCatalog
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MealOptionCatalog we want to update
   *   }
   * })
   */
  upsert<T extends MealOptionCatalogUpsertArgs>(args: Prisma.SelectSubset<T, MealOptionCatalogUpsertArgs<ExtArgs>>): Prisma.Prisma__MealOptionCatalogClient<runtime.Types.Result.GetResult<Prisma.$MealOptionCatalogPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MealOptionCatalogs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogCountArgs} args - Arguments to filter MealOptionCatalogs to count.
   * @example
   * // Count the number of MealOptionCatalogs
   * const count = await prisma.mealOptionCatalog.count({
   *   where: {
   *     // ... the filter for the MealOptionCatalogs we want to count
   *   }
   * })
  **/
  count<T extends MealOptionCatalogCountArgs>(
    args?: Prisma.Subset<T, MealOptionCatalogCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MealOptionCatalogCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MealOptionCatalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MealOptionCatalogAggregateArgs>(args: Prisma.Subset<T, MealOptionCatalogAggregateArgs>): Prisma.PrismaPromise<GetMealOptionCatalogAggregateType<T>>

  /**
   * Group by MealOptionCatalog.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MealOptionCatalogGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MealOptionCatalogGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MealOptionCatalogGroupByArgs['orderBy'] }
      : { orderBy?: MealOptionCatalogGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MealOptionCatalogGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMealOptionCatalogGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MealOptionCatalog model
 */
readonly fields: MealOptionCatalogFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MealOptionCatalog.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MealOptionCatalogClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MealOptionCatalog model
 */
export interface MealOptionCatalogFieldRefs {
  readonly id: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly title: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly windowType: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly absorptionType: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly dietaryBuckets: Prisma.FieldRef<"MealOptionCatalog", 'String[]'>
  readonly baseMacros: Prisma.FieldRef<"MealOptionCatalog", 'Json'>
  readonly keyIngredient: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly ingredients: Prisma.FieldRef<"MealOptionCatalog", 'Json'>
  readonly prepMinutes: Prisma.FieldRef<"MealOptionCatalog", 'Int'>
  readonly constraintTags: Prisma.FieldRef<"MealOptionCatalog", 'String[]'>
  readonly source: Prisma.FieldRef<"MealOptionCatalog", 'String'>
  readonly createdAt: Prisma.FieldRef<"MealOptionCatalog", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MealOptionCatalog", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MealOptionCatalog findUnique
 */
export type MealOptionCatalogFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter, which MealOptionCatalog to fetch.
   */
  where: Prisma.MealOptionCatalogWhereUniqueInput
}

/**
 * MealOptionCatalog findUniqueOrThrow
 */
export type MealOptionCatalogFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter, which MealOptionCatalog to fetch.
   */
  where: Prisma.MealOptionCatalogWhereUniqueInput
}

/**
 * MealOptionCatalog findFirst
 */
export type MealOptionCatalogFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter, which MealOptionCatalog to fetch.
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MealOptionCatalogs to fetch.
   */
  orderBy?: Prisma.MealOptionCatalogOrderByWithRelationInput | Prisma.MealOptionCatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MealOptionCatalogs.
   */
  cursor?: Prisma.MealOptionCatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MealOptionCatalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MealOptionCatalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MealOptionCatalogs.
   */
  distinct?: Prisma.MealOptionCatalogScalarFieldEnum | Prisma.MealOptionCatalogScalarFieldEnum[]
}

/**
 * MealOptionCatalog findFirstOrThrow
 */
export type MealOptionCatalogFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter, which MealOptionCatalog to fetch.
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MealOptionCatalogs to fetch.
   */
  orderBy?: Prisma.MealOptionCatalogOrderByWithRelationInput | Prisma.MealOptionCatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MealOptionCatalogs.
   */
  cursor?: Prisma.MealOptionCatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MealOptionCatalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MealOptionCatalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MealOptionCatalogs.
   */
  distinct?: Prisma.MealOptionCatalogScalarFieldEnum | Prisma.MealOptionCatalogScalarFieldEnum[]
}

/**
 * MealOptionCatalog findMany
 */
export type MealOptionCatalogFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter, which MealOptionCatalogs to fetch.
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MealOptionCatalogs to fetch.
   */
  orderBy?: Prisma.MealOptionCatalogOrderByWithRelationInput | Prisma.MealOptionCatalogOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MealOptionCatalogs.
   */
  cursor?: Prisma.MealOptionCatalogWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MealOptionCatalogs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MealOptionCatalogs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MealOptionCatalogs.
   */
  distinct?: Prisma.MealOptionCatalogScalarFieldEnum | Prisma.MealOptionCatalogScalarFieldEnum[]
}

/**
 * MealOptionCatalog create
 */
export type MealOptionCatalogCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * The data needed to create a MealOptionCatalog.
   */
  data: Prisma.XOR<Prisma.MealOptionCatalogCreateInput, Prisma.MealOptionCatalogUncheckedCreateInput>
}

/**
 * MealOptionCatalog createMany
 */
export type MealOptionCatalogCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MealOptionCatalogs.
   */
  data: Prisma.MealOptionCatalogCreateManyInput | Prisma.MealOptionCatalogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MealOptionCatalog createManyAndReturn
 */
export type MealOptionCatalogCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * The data used to create many MealOptionCatalogs.
   */
  data: Prisma.MealOptionCatalogCreateManyInput | Prisma.MealOptionCatalogCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MealOptionCatalog update
 */
export type MealOptionCatalogUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * The data needed to update a MealOptionCatalog.
   */
  data: Prisma.XOR<Prisma.MealOptionCatalogUpdateInput, Prisma.MealOptionCatalogUncheckedUpdateInput>
  /**
   * Choose, which MealOptionCatalog to update.
   */
  where: Prisma.MealOptionCatalogWhereUniqueInput
}

/**
 * MealOptionCatalog updateMany
 */
export type MealOptionCatalogUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MealOptionCatalogs.
   */
  data: Prisma.XOR<Prisma.MealOptionCatalogUpdateManyMutationInput, Prisma.MealOptionCatalogUncheckedUpdateManyInput>
  /**
   * Filter which MealOptionCatalogs to update
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * Limit how many MealOptionCatalogs to update.
   */
  limit?: number
}

/**
 * MealOptionCatalog updateManyAndReturn
 */
export type MealOptionCatalogUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * The data used to update MealOptionCatalogs.
   */
  data: Prisma.XOR<Prisma.MealOptionCatalogUpdateManyMutationInput, Prisma.MealOptionCatalogUncheckedUpdateManyInput>
  /**
   * Filter which MealOptionCatalogs to update
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * Limit how many MealOptionCatalogs to update.
   */
  limit?: number
}

/**
 * MealOptionCatalog upsert
 */
export type MealOptionCatalogUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * The filter to search for the MealOptionCatalog to update in case it exists.
   */
  where: Prisma.MealOptionCatalogWhereUniqueInput
  /**
   * In case the MealOptionCatalog found by the `where` argument doesn't exist, create a new MealOptionCatalog with this data.
   */
  create: Prisma.XOR<Prisma.MealOptionCatalogCreateInput, Prisma.MealOptionCatalogUncheckedCreateInput>
  /**
   * In case the MealOptionCatalog was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MealOptionCatalogUpdateInput, Prisma.MealOptionCatalogUncheckedUpdateInput>
}

/**
 * MealOptionCatalog delete
 */
export type MealOptionCatalogDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
  /**
   * Filter which MealOptionCatalog to delete.
   */
  where: Prisma.MealOptionCatalogWhereUniqueInput
}

/**
 * MealOptionCatalog deleteMany
 */
export type MealOptionCatalogDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MealOptionCatalogs to delete
   */
  where?: Prisma.MealOptionCatalogWhereInput
  /**
   * Limit how many MealOptionCatalogs to delete.
   */
  limit?: number
}

/**
 * MealOptionCatalog without action
 */
export type MealOptionCatalogDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MealOptionCatalog
   */
  select?: Prisma.MealOptionCatalogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MealOptionCatalog
   */
  omit?: Prisma.MealOptionCatalogOmit<ExtArgs> | null
}
