
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PartnerCampaignRedemption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PartnerCampaignRedemption
 * 
 */
export type PartnerCampaignRedemptionModel = runtime.Types.Result.DefaultSelection<Prisma.$PartnerCampaignRedemptionPayload>

export type AggregatePartnerCampaignRedemption = {
  _count: PartnerCampaignRedemptionCountAggregateOutputType | null
  _min: PartnerCampaignRedemptionMinAggregateOutputType | null
  _max: PartnerCampaignRedemptionMaxAggregateOutputType | null
}

export type PartnerCampaignRedemptionMinAggregateOutputType = {
  id: string | null
  campaignId: string | null
  userId: string | null
  grantedTier: $Enums.SubscriptionTier | null
  startsAt: Date | null
  endsAt: Date | null
  redeemedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerCampaignRedemptionMaxAggregateOutputType = {
  id: string | null
  campaignId: string | null
  userId: string | null
  grantedTier: $Enums.SubscriptionTier | null
  startsAt: Date | null
  endsAt: Date | null
  redeemedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PartnerCampaignRedemptionCountAggregateOutputType = {
  id: number
  campaignId: number
  userId: number
  grantedTier: number
  startsAt: number
  endsAt: number
  redeemedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PartnerCampaignRedemptionMinAggregateInputType = {
  id?: true
  campaignId?: true
  userId?: true
  grantedTier?: true
  startsAt?: true
  endsAt?: true
  redeemedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerCampaignRedemptionMaxAggregateInputType = {
  id?: true
  campaignId?: true
  userId?: true
  grantedTier?: true
  startsAt?: true
  endsAt?: true
  redeemedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type PartnerCampaignRedemptionCountAggregateInputType = {
  id?: true
  campaignId?: true
  userId?: true
  grantedTier?: true
  startsAt?: true
  endsAt?: true
  redeemedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PartnerCampaignRedemptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerCampaignRedemption to aggregate.
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerCampaignRedemptions to fetch.
   */
  orderBy?: Prisma.PartnerCampaignRedemptionOrderByWithRelationInput | Prisma.PartnerCampaignRedemptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerCampaignRedemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerCampaignRedemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PartnerCampaignRedemptions
  **/
  _count?: true | PartnerCampaignRedemptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PartnerCampaignRedemptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PartnerCampaignRedemptionMaxAggregateInputType
}

export type GetPartnerCampaignRedemptionAggregateType<T extends PartnerCampaignRedemptionAggregateArgs> = {
      [P in keyof T & keyof AggregatePartnerCampaignRedemption]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePartnerCampaignRedemption[P]>
    : Prisma.GetScalarType<T[P], AggregatePartnerCampaignRedemption[P]>
}




export type PartnerCampaignRedemptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  orderBy?: Prisma.PartnerCampaignRedemptionOrderByWithAggregationInput | Prisma.PartnerCampaignRedemptionOrderByWithAggregationInput[]
  by: Prisma.PartnerCampaignRedemptionScalarFieldEnum[] | Prisma.PartnerCampaignRedemptionScalarFieldEnum
  having?: Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PartnerCampaignRedemptionCountAggregateInputType | true
  _min?: PartnerCampaignRedemptionMinAggregateInputType
  _max?: PartnerCampaignRedemptionMaxAggregateInputType
}

export type PartnerCampaignRedemptionGroupByOutputType = {
  id: string
  campaignId: string
  userId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date
  endsAt: Date
  redeemedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: PartnerCampaignRedemptionCountAggregateOutputType | null
  _min: PartnerCampaignRedemptionMinAggregateOutputType | null
  _max: PartnerCampaignRedemptionMaxAggregateOutputType | null
}

export type GetPartnerCampaignRedemptionGroupByPayload<T extends PartnerCampaignRedemptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PartnerCampaignRedemptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PartnerCampaignRedemptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PartnerCampaignRedemptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PartnerCampaignRedemptionGroupByOutputType[P]>
      }
    >
  >



export type PartnerCampaignRedemptionWhereInput = {
  AND?: Prisma.PartnerCampaignRedemptionWhereInput | Prisma.PartnerCampaignRedemptionWhereInput[]
  OR?: Prisma.PartnerCampaignRedemptionWhereInput[]
  NOT?: Prisma.PartnerCampaignRedemptionWhereInput | Prisma.PartnerCampaignRedemptionWhereInput[]
  id?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  campaignId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  userId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  grantedTier?: Prisma.EnumSubscriptionTierFilter<"PartnerCampaignRedemption"> | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  redeemedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  campaign?: Prisma.XOR<Prisma.PartnerCampaignScalarRelationFilter, Prisma.PartnerCampaignWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PartnerCampaignRedemptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  grantedTier?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  redeemedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  campaign?: Prisma.PartnerCampaignOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type PartnerCampaignRedemptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  campaignId_userId?: Prisma.PartnerCampaignRedemptionCampaignIdUserIdCompoundUniqueInput
  AND?: Prisma.PartnerCampaignRedemptionWhereInput | Prisma.PartnerCampaignRedemptionWhereInput[]
  OR?: Prisma.PartnerCampaignRedemptionWhereInput[]
  NOT?: Prisma.PartnerCampaignRedemptionWhereInput | Prisma.PartnerCampaignRedemptionWhereInput[]
  campaignId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  userId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  grantedTier?: Prisma.EnumSubscriptionTierFilter<"PartnerCampaignRedemption"> | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  redeemedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  campaign?: Prisma.XOR<Prisma.PartnerCampaignScalarRelationFilter, Prisma.PartnerCampaignWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "campaignId_userId">

export type PartnerCampaignRedemptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  grantedTier?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  redeemedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PartnerCampaignRedemptionCountOrderByAggregateInput
  _max?: Prisma.PartnerCampaignRedemptionMaxOrderByAggregateInput
  _min?: Prisma.PartnerCampaignRedemptionMinOrderByAggregateInput
}

export type PartnerCampaignRedemptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput | Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput | Prisma.PartnerCampaignRedemptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PartnerCampaignRedemption"> | string
  campaignId?: Prisma.StringWithAggregatesFilter<"PartnerCampaignRedemption"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PartnerCampaignRedemption"> | string
  grantedTier?: Prisma.EnumSubscriptionTierWithAggregatesFilter<"PartnerCampaignRedemption"> | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerCampaignRedemption"> | Date | string
  endsAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerCampaignRedemption"> | Date | string
  redeemedAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerCampaignRedemption"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerCampaignRedemption"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PartnerCampaignRedemption"> | Date | string
}

export type PartnerCampaignRedemptionCreateInput = {
  id?: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  campaign: Prisma.PartnerCampaignCreateNestedOneWithoutRedemptionsInput
  user: Prisma.UserCreateNestedOneWithoutPartnerCampaignRedemptionsInput
}

export type PartnerCampaignRedemptionUncheckedCreateInput = {
  id?: string
  campaignId: string
  userId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  campaign?: Prisma.PartnerCampaignUpdateOneRequiredWithoutRedemptionsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutPartnerCampaignRedemptionsNestedInput
}

export type PartnerCampaignRedemptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionCreateManyInput = {
  id?: string
  campaignId: string
  userId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionListRelationFilter = {
  every?: Prisma.PartnerCampaignRedemptionWhereInput
  some?: Prisma.PartnerCampaignRedemptionWhereInput
  none?: Prisma.PartnerCampaignRedemptionWhereInput
}

export type PartnerCampaignRedemptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PartnerCampaignRedemptionCampaignIdUserIdCompoundUniqueInput = {
  campaignId: string
  userId: string
}

export type PartnerCampaignRedemptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  grantedTier?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  redeemedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerCampaignRedemptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  grantedTier?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  redeemedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerCampaignRedemptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  campaignId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  grantedTier?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  redeemedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PartnerCampaignRedemptionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput> | Prisma.PartnerCampaignRedemptionCreateWithoutUserInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyUserInputEnvelope
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
}

export type PartnerCampaignRedemptionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput> | Prisma.PartnerCampaignRedemptionCreateWithoutUserInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyUserInputEnvelope
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
}

export type PartnerCampaignRedemptionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput> | Prisma.PartnerCampaignRedemptionCreateWithoutUserInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutUserInput | Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyUserInputEnvelope
  set?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  disconnect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  delete?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  update?: Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutUserInput | Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutUserInput | Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
}

export type PartnerCampaignRedemptionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput> | Prisma.PartnerCampaignRedemptionCreateWithoutUserInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutUserInput | Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyUserInputEnvelope
  set?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  disconnect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  delete?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  update?: Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutUserInput | Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutUserInput | Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
}

export type PartnerCampaignRedemptionCreateNestedManyWithoutCampaignInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput> | Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyCampaignInputEnvelope
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
}

export type PartnerCampaignRedemptionUncheckedCreateNestedManyWithoutCampaignInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput> | Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyCampaignInputEnvelope
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
}

export type PartnerCampaignRedemptionUpdateManyWithoutCampaignNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput> | Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput[]
  upsert?: Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutCampaignInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyCampaignInputEnvelope
  set?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  disconnect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  delete?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  update?: Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutCampaignInput[]
  updateMany?: Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutCampaignInput[]
  deleteMany?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
}

export type PartnerCampaignRedemptionUncheckedUpdateManyWithoutCampaignNestedInput = {
  create?: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput> | Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput[] | Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput[]
  connectOrCreate?: Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput | Prisma.PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput[]
  upsert?: Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutCampaignInput[]
  createMany?: Prisma.PartnerCampaignRedemptionCreateManyCampaignInputEnvelope
  set?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  disconnect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  delete?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  connect?: Prisma.PartnerCampaignRedemptionWhereUniqueInput | Prisma.PartnerCampaignRedemptionWhereUniqueInput[]
  update?: Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutCampaignInput[]
  updateMany?: Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutCampaignInput | Prisma.PartnerCampaignRedemptionUpdateManyWithWhereWithoutCampaignInput[]
  deleteMany?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
}

export type PartnerCampaignRedemptionCreateWithoutUserInput = {
  id?: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  campaign: Prisma.PartnerCampaignCreateNestedOneWithoutRedemptionsInput
}

export type PartnerCampaignRedemptionUncheckedCreateWithoutUserInput = {
  id?: string
  campaignId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionCreateOrConnectWithoutUserInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput>
}

export type PartnerCampaignRedemptionCreateManyUserInputEnvelope = {
  data: Prisma.PartnerCampaignRedemptionCreateManyUserInput | Prisma.PartnerCampaignRedemptionCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  update: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutUserInput>
}

export type PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateWithoutUserInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateWithoutUserInput>
}

export type PartnerCampaignRedemptionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.PartnerCampaignRedemptionScalarWhereInput
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateManyMutationInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateManyWithoutUserInput>
}

export type PartnerCampaignRedemptionScalarWhereInput = {
  AND?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
  OR?: Prisma.PartnerCampaignRedemptionScalarWhereInput[]
  NOT?: Prisma.PartnerCampaignRedemptionScalarWhereInput | Prisma.PartnerCampaignRedemptionScalarWhereInput[]
  id?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  campaignId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  userId?: Prisma.StringFilter<"PartnerCampaignRedemption"> | string
  grantedTier?: Prisma.EnumSubscriptionTierFilter<"PartnerCampaignRedemption"> | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  redeemedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PartnerCampaignRedemption"> | Date | string
}

export type PartnerCampaignRedemptionCreateWithoutCampaignInput = {
  id?: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPartnerCampaignRedemptionsInput
}

export type PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput = {
  id?: string
  userId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionCreateOrConnectWithoutCampaignInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  create: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput>
}

export type PartnerCampaignRedemptionCreateManyCampaignInputEnvelope = {
  data: Prisma.PartnerCampaignRedemptionCreateManyCampaignInput | Prisma.PartnerCampaignRedemptionCreateManyCampaignInput[]
  skipDuplicates?: boolean
}

export type PartnerCampaignRedemptionUpsertWithWhereUniqueWithoutCampaignInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  update: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateWithoutCampaignInput>
  create: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedCreateWithoutCampaignInput>
}

export type PartnerCampaignRedemptionUpdateWithWhereUniqueWithoutCampaignInput = {
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateWithoutCampaignInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateWithoutCampaignInput>
}

export type PartnerCampaignRedemptionUpdateManyWithWhereWithoutCampaignInput = {
  where: Prisma.PartnerCampaignRedemptionScalarWhereInput
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateManyMutationInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateManyWithoutCampaignInput>
}

export type PartnerCampaignRedemptionCreateManyUserInput = {
  id?: string
  campaignId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  campaign?: Prisma.PartnerCampaignUpdateOneRequiredWithoutRedemptionsNestedInput
}

export type PartnerCampaignRedemptionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  campaignId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionCreateManyCampaignInput = {
  id?: string
  userId: string
  grantedTier: $Enums.SubscriptionTier
  startsAt: Date | string
  endsAt: Date | string
  redeemedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PartnerCampaignRedemptionUpdateWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPartnerCampaignRedemptionsNestedInput
}

export type PartnerCampaignRedemptionUncheckedUpdateWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PartnerCampaignRedemptionUncheckedUpdateManyWithoutCampaignInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedTier?: Prisma.EnumSubscriptionTierFieldUpdateOperationsInput | $Enums.SubscriptionTier
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  redeemedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PartnerCampaignRedemptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  userId?: boolean
  grantedTier?: boolean
  startsAt?: boolean
  endsAt?: boolean
  redeemedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerCampaignRedemption"]>

export type PartnerCampaignRedemptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  userId?: boolean
  grantedTier?: boolean
  startsAt?: boolean
  endsAt?: boolean
  redeemedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerCampaignRedemption"]>

export type PartnerCampaignRedemptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  campaignId?: boolean
  userId?: boolean
  grantedTier?: boolean
  startsAt?: boolean
  endsAt?: boolean
  redeemedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["partnerCampaignRedemption"]>

export type PartnerCampaignRedemptionSelectScalar = {
  id?: boolean
  campaignId?: boolean
  userId?: boolean
  grantedTier?: boolean
  startsAt?: boolean
  endsAt?: boolean
  redeemedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PartnerCampaignRedemptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "campaignId" | "userId" | "grantedTier" | "startsAt" | "endsAt" | "redeemedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["partnerCampaignRedemption"]>
export type PartnerCampaignRedemptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PartnerCampaignRedemptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PartnerCampaignRedemptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  campaign?: boolean | Prisma.PartnerCampaignDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PartnerCampaignRedemptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PartnerCampaignRedemption"
  objects: {
    campaign: Prisma.$PartnerCampaignPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    campaignId: string
    userId: string
    grantedTier: $Enums.SubscriptionTier
    startsAt: Date
    endsAt: Date
    redeemedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["partnerCampaignRedemption"]>
  composites: {}
}

export type PartnerCampaignRedemptionGetPayload<S extends boolean | null | undefined | PartnerCampaignRedemptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload, S>

export type PartnerCampaignRedemptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PartnerCampaignRedemptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PartnerCampaignRedemptionCountAggregateInputType | true
  }

export interface PartnerCampaignRedemptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PartnerCampaignRedemption'], meta: { name: 'PartnerCampaignRedemption' } }
  /**
   * Find zero or one PartnerCampaignRedemption that matches the filter.
   * @param {PartnerCampaignRedemptionFindUniqueArgs} args - Arguments to find a PartnerCampaignRedemption
   * @example
   * // Get one PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PartnerCampaignRedemptionFindUniqueArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PartnerCampaignRedemption that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PartnerCampaignRedemptionFindUniqueOrThrowArgs} args - Arguments to find a PartnerCampaignRedemption
   * @example
   * // Get one PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PartnerCampaignRedemptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerCampaignRedemption that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionFindFirstArgs} args - Arguments to find a PartnerCampaignRedemption
   * @example
   * // Get one PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PartnerCampaignRedemptionFindFirstArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PartnerCampaignRedemption that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionFindFirstOrThrowArgs} args - Arguments to find a PartnerCampaignRedemption
   * @example
   * // Get one PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PartnerCampaignRedemptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PartnerCampaignRedemptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PartnerCampaignRedemptions
   * const partnerCampaignRedemptions = await prisma.partnerCampaignRedemption.findMany()
   * 
   * // Get first 10 PartnerCampaignRedemptions
   * const partnerCampaignRedemptions = await prisma.partnerCampaignRedemption.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const partnerCampaignRedemptionWithIdOnly = await prisma.partnerCampaignRedemption.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PartnerCampaignRedemptionFindManyArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PartnerCampaignRedemption.
   * @param {PartnerCampaignRedemptionCreateArgs} args - Arguments to create a PartnerCampaignRedemption.
   * @example
   * // Create one PartnerCampaignRedemption
   * const PartnerCampaignRedemption = await prisma.partnerCampaignRedemption.create({
   *   data: {
   *     // ... data to create a PartnerCampaignRedemption
   *   }
   * })
   * 
   */
  create<T extends PartnerCampaignRedemptionCreateArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionCreateArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PartnerCampaignRedemptions.
   * @param {PartnerCampaignRedemptionCreateManyArgs} args - Arguments to create many PartnerCampaignRedemptions.
   * @example
   * // Create many PartnerCampaignRedemptions
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PartnerCampaignRedemptionCreateManyArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PartnerCampaignRedemptions and returns the data saved in the database.
   * @param {PartnerCampaignRedemptionCreateManyAndReturnArgs} args - Arguments to create many PartnerCampaignRedemptions.
   * @example
   * // Create many PartnerCampaignRedemptions
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PartnerCampaignRedemptions and only return the `id`
   * const partnerCampaignRedemptionWithIdOnly = await prisma.partnerCampaignRedemption.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PartnerCampaignRedemptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PartnerCampaignRedemption.
   * @param {PartnerCampaignRedemptionDeleteArgs} args - Arguments to delete one PartnerCampaignRedemption.
   * @example
   * // Delete one PartnerCampaignRedemption
   * const PartnerCampaignRedemption = await prisma.partnerCampaignRedemption.delete({
   *   where: {
   *     // ... filter to delete one PartnerCampaignRedemption
   *   }
   * })
   * 
   */
  delete<T extends PartnerCampaignRedemptionDeleteArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionDeleteArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PartnerCampaignRedemption.
   * @param {PartnerCampaignRedemptionUpdateArgs} args - Arguments to update one PartnerCampaignRedemption.
   * @example
   * // Update one PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PartnerCampaignRedemptionUpdateArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionUpdateArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PartnerCampaignRedemptions.
   * @param {PartnerCampaignRedemptionDeleteManyArgs} args - Arguments to filter PartnerCampaignRedemptions to delete.
   * @example
   * // Delete a few PartnerCampaignRedemptions
   * const { count } = await prisma.partnerCampaignRedemption.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PartnerCampaignRedemptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, PartnerCampaignRedemptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PartnerCampaignRedemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PartnerCampaignRedemptions
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PartnerCampaignRedemptionUpdateManyArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PartnerCampaignRedemptions and returns the data updated in the database.
   * @param {PartnerCampaignRedemptionUpdateManyAndReturnArgs} args - Arguments to update many PartnerCampaignRedemptions.
   * @example
   * // Update many PartnerCampaignRedemptions
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PartnerCampaignRedemptions and only return the `id`
   * const partnerCampaignRedemptionWithIdOnly = await prisma.partnerCampaignRedemption.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PartnerCampaignRedemptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PartnerCampaignRedemption.
   * @param {PartnerCampaignRedemptionUpsertArgs} args - Arguments to update or create a PartnerCampaignRedemption.
   * @example
   * // Update or create a PartnerCampaignRedemption
   * const partnerCampaignRedemption = await prisma.partnerCampaignRedemption.upsert({
   *   create: {
   *     // ... data to create a PartnerCampaignRedemption
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PartnerCampaignRedemption we want to update
   *   }
   * })
   */
  upsert<T extends PartnerCampaignRedemptionUpsertArgs>(args: Prisma.SelectSubset<T, PartnerCampaignRedemptionUpsertArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignRedemptionClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignRedemptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PartnerCampaignRedemptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionCountArgs} args - Arguments to filter PartnerCampaignRedemptions to count.
   * @example
   * // Count the number of PartnerCampaignRedemptions
   * const count = await prisma.partnerCampaignRedemption.count({
   *   where: {
   *     // ... the filter for the PartnerCampaignRedemptions we want to count
   *   }
   * })
  **/
  count<T extends PartnerCampaignRedemptionCountArgs>(
    args?: Prisma.Subset<T, PartnerCampaignRedemptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PartnerCampaignRedemptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PartnerCampaignRedemption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PartnerCampaignRedemptionAggregateArgs>(args: Prisma.Subset<T, PartnerCampaignRedemptionAggregateArgs>): Prisma.PrismaPromise<GetPartnerCampaignRedemptionAggregateType<T>>

  /**
   * Group by PartnerCampaignRedemption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PartnerCampaignRedemptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PartnerCampaignRedemptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PartnerCampaignRedemptionGroupByArgs['orderBy'] }
      : { orderBy?: PartnerCampaignRedemptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PartnerCampaignRedemptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPartnerCampaignRedemptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PartnerCampaignRedemption model
 */
readonly fields: PartnerCampaignRedemptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PartnerCampaignRedemption.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PartnerCampaignRedemptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  campaign<T extends Prisma.PartnerCampaignDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PartnerCampaignDefaultArgs<ExtArgs>>): Prisma.Prisma__PartnerCampaignClient<runtime.Types.Result.GetResult<Prisma.$PartnerCampaignPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PartnerCampaignRedemption model
 */
export interface PartnerCampaignRedemptionFieldRefs {
  readonly id: Prisma.FieldRef<"PartnerCampaignRedemption", 'String'>
  readonly campaignId: Prisma.FieldRef<"PartnerCampaignRedemption", 'String'>
  readonly userId: Prisma.FieldRef<"PartnerCampaignRedemption", 'String'>
  readonly grantedTier: Prisma.FieldRef<"PartnerCampaignRedemption", 'SubscriptionTier'>
  readonly startsAt: Prisma.FieldRef<"PartnerCampaignRedemption", 'DateTime'>
  readonly endsAt: Prisma.FieldRef<"PartnerCampaignRedemption", 'DateTime'>
  readonly redeemedAt: Prisma.FieldRef<"PartnerCampaignRedemption", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"PartnerCampaignRedemption", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PartnerCampaignRedemption", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PartnerCampaignRedemption findUnique
 */
export type PartnerCampaignRedemptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter, which PartnerCampaignRedemption to fetch.
   */
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
}

/**
 * PartnerCampaignRedemption findUniqueOrThrow
 */
export type PartnerCampaignRedemptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter, which PartnerCampaignRedemption to fetch.
   */
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
}

/**
 * PartnerCampaignRedemption findFirst
 */
export type PartnerCampaignRedemptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter, which PartnerCampaignRedemption to fetch.
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerCampaignRedemptions to fetch.
   */
  orderBy?: Prisma.PartnerCampaignRedemptionOrderByWithRelationInput | Prisma.PartnerCampaignRedemptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerCampaignRedemptions.
   */
  cursor?: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerCampaignRedemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerCampaignRedemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerCampaignRedemptions.
   */
  distinct?: Prisma.PartnerCampaignRedemptionScalarFieldEnum | Prisma.PartnerCampaignRedemptionScalarFieldEnum[]
}

/**
 * PartnerCampaignRedemption findFirstOrThrow
 */
export type PartnerCampaignRedemptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter, which PartnerCampaignRedemption to fetch.
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerCampaignRedemptions to fetch.
   */
  orderBy?: Prisma.PartnerCampaignRedemptionOrderByWithRelationInput | Prisma.PartnerCampaignRedemptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PartnerCampaignRedemptions.
   */
  cursor?: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerCampaignRedemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerCampaignRedemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerCampaignRedemptions.
   */
  distinct?: Prisma.PartnerCampaignRedemptionScalarFieldEnum | Prisma.PartnerCampaignRedemptionScalarFieldEnum[]
}

/**
 * PartnerCampaignRedemption findMany
 */
export type PartnerCampaignRedemptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter, which PartnerCampaignRedemptions to fetch.
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PartnerCampaignRedemptions to fetch.
   */
  orderBy?: Prisma.PartnerCampaignRedemptionOrderByWithRelationInput | Prisma.PartnerCampaignRedemptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PartnerCampaignRedemptions.
   */
  cursor?: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PartnerCampaignRedemptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PartnerCampaignRedemptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PartnerCampaignRedemptions.
   */
  distinct?: Prisma.PartnerCampaignRedemptionScalarFieldEnum | Prisma.PartnerCampaignRedemptionScalarFieldEnum[]
}

/**
 * PartnerCampaignRedemption create
 */
export type PartnerCampaignRedemptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * The data needed to create a PartnerCampaignRedemption.
   */
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateInput, Prisma.PartnerCampaignRedemptionUncheckedCreateInput>
}

/**
 * PartnerCampaignRedemption createMany
 */
export type PartnerCampaignRedemptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PartnerCampaignRedemptions.
   */
  data: Prisma.PartnerCampaignRedemptionCreateManyInput | Prisma.PartnerCampaignRedemptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PartnerCampaignRedemption createManyAndReturn
 */
export type PartnerCampaignRedemptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * The data used to create many PartnerCampaignRedemptions.
   */
  data: Prisma.PartnerCampaignRedemptionCreateManyInput | Prisma.PartnerCampaignRedemptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PartnerCampaignRedemption update
 */
export type PartnerCampaignRedemptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * The data needed to update a PartnerCampaignRedemption.
   */
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateInput>
  /**
   * Choose, which PartnerCampaignRedemption to update.
   */
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
}

/**
 * PartnerCampaignRedemption updateMany
 */
export type PartnerCampaignRedemptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PartnerCampaignRedemptions.
   */
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateManyMutationInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateManyInput>
  /**
   * Filter which PartnerCampaignRedemptions to update
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * Limit how many PartnerCampaignRedemptions to update.
   */
  limit?: number
}

/**
 * PartnerCampaignRedemption updateManyAndReturn
 */
export type PartnerCampaignRedemptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * The data used to update PartnerCampaignRedemptions.
   */
  data: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateManyMutationInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateManyInput>
  /**
   * Filter which PartnerCampaignRedemptions to update
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * Limit how many PartnerCampaignRedemptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PartnerCampaignRedemption upsert
 */
export type PartnerCampaignRedemptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * The filter to search for the PartnerCampaignRedemption to update in case it exists.
   */
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
  /**
   * In case the PartnerCampaignRedemption found by the `where` argument doesn't exist, create a new PartnerCampaignRedemption with this data.
   */
  create: Prisma.XOR<Prisma.PartnerCampaignRedemptionCreateInput, Prisma.PartnerCampaignRedemptionUncheckedCreateInput>
  /**
   * In case the PartnerCampaignRedemption was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PartnerCampaignRedemptionUpdateInput, Prisma.PartnerCampaignRedemptionUncheckedUpdateInput>
}

/**
 * PartnerCampaignRedemption delete
 */
export type PartnerCampaignRedemptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
  /**
   * Filter which PartnerCampaignRedemption to delete.
   */
  where: Prisma.PartnerCampaignRedemptionWhereUniqueInput
}

/**
 * PartnerCampaignRedemption deleteMany
 */
export type PartnerCampaignRedemptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PartnerCampaignRedemptions to delete
   */
  where?: Prisma.PartnerCampaignRedemptionWhereInput
  /**
   * Limit how many PartnerCampaignRedemptions to delete.
   */
  limit?: number
}

/**
 * PartnerCampaignRedemption without action
 */
export type PartnerCampaignRedemptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PartnerCampaignRedemption
   */
  select?: Prisma.PartnerCampaignRedemptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PartnerCampaignRedemption
   */
  omit?: Prisma.PartnerCampaignRedemptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PartnerCampaignRedemptionInclude<ExtArgs> | null
}
