
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TrainingBlock` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TrainingBlock
 * 
 */
export type TrainingBlockModel = runtime.Types.Result.DefaultSelection<Prisma.$TrainingBlockPayload>

export type AggregateTrainingBlock = {
  _count: TrainingBlockCountAggregateOutputType | null
  _avg: TrainingBlockAvgAggregateOutputType | null
  _sum: TrainingBlockSumAggregateOutputType | null
  _min: TrainingBlockMinAggregateOutputType | null
  _max: TrainingBlockMaxAggregateOutputType | null
}

export type TrainingBlockAvgAggregateOutputType = {
  order: number | null
  durationWeeks: number | null
  recoveryWeekIndex: number | null
}

export type TrainingBlockSumAggregateOutputType = {
  order: number | null
  durationWeeks: number | null
  recoveryWeekIndex: number | null
}

export type TrainingBlockMinAggregateOutputType = {
  id: string | null
  trainingPlanId: string | null
  order: number | null
  name: string | null
  type: string | null
  primaryFocus: string | null
  startDate: Date | null
  durationWeeks: number | null
  recoveryWeekIndex: number | null
  progressionLogic: string | null
  createdAt: Date | null
  updatedAt: Date | null
  description: string | null
}

export type TrainingBlockMaxAggregateOutputType = {
  id: string | null
  trainingPlanId: string | null
  order: number | null
  name: string | null
  type: string | null
  primaryFocus: string | null
  startDate: Date | null
  durationWeeks: number | null
  recoveryWeekIndex: number | null
  progressionLogic: string | null
  createdAt: Date | null
  updatedAt: Date | null
  description: string | null
}

export type TrainingBlockCountAggregateOutputType = {
  id: number
  trainingPlanId: number
  order: number
  name: number
  type: number
  primaryFocus: number
  startDate: number
  durationWeeks: number
  recoveryWeekIndex: number
  progressionLogic: number
  createdAt: number
  updatedAt: number
  description: number
  _all: number
}


export type TrainingBlockAvgAggregateInputType = {
  order?: true
  durationWeeks?: true
  recoveryWeekIndex?: true
}

export type TrainingBlockSumAggregateInputType = {
  order?: true
  durationWeeks?: true
  recoveryWeekIndex?: true
}

export type TrainingBlockMinAggregateInputType = {
  id?: true
  trainingPlanId?: true
  order?: true
  name?: true
  type?: true
  primaryFocus?: true
  startDate?: true
  durationWeeks?: true
  recoveryWeekIndex?: true
  progressionLogic?: true
  createdAt?: true
  updatedAt?: true
  description?: true
}

export type TrainingBlockMaxAggregateInputType = {
  id?: true
  trainingPlanId?: true
  order?: true
  name?: true
  type?: true
  primaryFocus?: true
  startDate?: true
  durationWeeks?: true
  recoveryWeekIndex?: true
  progressionLogic?: true
  createdAt?: true
  updatedAt?: true
  description?: true
}

export type TrainingBlockCountAggregateInputType = {
  id?: true
  trainingPlanId?: true
  order?: true
  name?: true
  type?: true
  primaryFocus?: true
  startDate?: true
  durationWeeks?: true
  recoveryWeekIndex?: true
  progressionLogic?: true
  createdAt?: true
  updatedAt?: true
  description?: true
  _all?: true
}

export type TrainingBlockAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrainingBlock to aggregate.
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainingBlocks to fetch.
   */
  orderBy?: Prisma.TrainingBlockOrderByWithRelationInput | Prisma.TrainingBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TrainingBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainingBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainingBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TrainingBlocks
  **/
  _count?: true | TrainingBlockCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TrainingBlockAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TrainingBlockSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TrainingBlockMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TrainingBlockMaxAggregateInputType
}

export type GetTrainingBlockAggregateType<T extends TrainingBlockAggregateArgs> = {
      [P in keyof T & keyof AggregateTrainingBlock]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTrainingBlock[P]>
    : Prisma.GetScalarType<T[P], AggregateTrainingBlock[P]>
}




export type TrainingBlockGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TrainingBlockWhereInput
  orderBy?: Prisma.TrainingBlockOrderByWithAggregationInput | Prisma.TrainingBlockOrderByWithAggregationInput[]
  by: Prisma.TrainingBlockScalarFieldEnum[] | Prisma.TrainingBlockScalarFieldEnum
  having?: Prisma.TrainingBlockScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TrainingBlockCountAggregateInputType | true
  _avg?: TrainingBlockAvgAggregateInputType
  _sum?: TrainingBlockSumAggregateInputType
  _min?: TrainingBlockMinAggregateInputType
  _max?: TrainingBlockMaxAggregateInputType
}

export type TrainingBlockGroupByOutputType = {
  id: string
  trainingPlanId: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date
  durationWeeks: number
  recoveryWeekIndex: number | null
  progressionLogic: string | null
  createdAt: Date
  updatedAt: Date
  description: string | null
  _count: TrainingBlockCountAggregateOutputType | null
  _avg: TrainingBlockAvgAggregateOutputType | null
  _sum: TrainingBlockSumAggregateOutputType | null
  _min: TrainingBlockMinAggregateOutputType | null
  _max: TrainingBlockMaxAggregateOutputType | null
}

export type GetTrainingBlockGroupByPayload<T extends TrainingBlockGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TrainingBlockGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TrainingBlockGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TrainingBlockGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TrainingBlockGroupByOutputType[P]>
      }
    >
  >



export type TrainingBlockWhereInput = {
  AND?: Prisma.TrainingBlockWhereInput | Prisma.TrainingBlockWhereInput[]
  OR?: Prisma.TrainingBlockWhereInput[]
  NOT?: Prisma.TrainingBlockWhereInput | Prisma.TrainingBlockWhereInput[]
  id?: Prisma.StringFilter<"TrainingBlock"> | string
  trainingPlanId?: Prisma.StringFilter<"TrainingBlock"> | string
  order?: Prisma.IntFilter<"TrainingBlock"> | number
  name?: Prisma.StringFilter<"TrainingBlock"> | string
  type?: Prisma.StringFilter<"TrainingBlock"> | string
  primaryFocus?: Prisma.StringFilter<"TrainingBlock"> | string
  startDate?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  durationWeeks?: Prisma.IntFilter<"TrainingBlock"> | number
  recoveryWeekIndex?: Prisma.IntNullableFilter<"TrainingBlock"> | number | null
  progressionLogic?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  description?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
  plan?: Prisma.XOR<Prisma.TrainingPlanScalarRelationFilter, Prisma.TrainingPlanWhereInput>
  weeks?: Prisma.TrainingWeekListRelationFilter
}

export type TrainingBlockOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  trainingPlanId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  primaryFocus?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  progressionLogic?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  plan?: Prisma.TrainingPlanOrderByWithRelationInput
  weeks?: Prisma.TrainingWeekOrderByRelationAggregateInput
}

export type TrainingBlockWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TrainingBlockWhereInput | Prisma.TrainingBlockWhereInput[]
  OR?: Prisma.TrainingBlockWhereInput[]
  NOT?: Prisma.TrainingBlockWhereInput | Prisma.TrainingBlockWhereInput[]
  trainingPlanId?: Prisma.StringFilter<"TrainingBlock"> | string
  order?: Prisma.IntFilter<"TrainingBlock"> | number
  name?: Prisma.StringFilter<"TrainingBlock"> | string
  type?: Prisma.StringFilter<"TrainingBlock"> | string
  primaryFocus?: Prisma.StringFilter<"TrainingBlock"> | string
  startDate?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  durationWeeks?: Prisma.IntFilter<"TrainingBlock"> | number
  recoveryWeekIndex?: Prisma.IntNullableFilter<"TrainingBlock"> | number | null
  progressionLogic?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  description?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
  plan?: Prisma.XOR<Prisma.TrainingPlanScalarRelationFilter, Prisma.TrainingPlanWhereInput>
  weeks?: Prisma.TrainingWeekListRelationFilter
}, "id">

export type TrainingBlockOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  trainingPlanId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  primaryFocus?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrderInput | Prisma.SortOrder
  progressionLogic?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TrainingBlockCountOrderByAggregateInput
  _avg?: Prisma.TrainingBlockAvgOrderByAggregateInput
  _max?: Prisma.TrainingBlockMaxOrderByAggregateInput
  _min?: Prisma.TrainingBlockMinOrderByAggregateInput
  _sum?: Prisma.TrainingBlockSumOrderByAggregateInput
}

export type TrainingBlockScalarWhereWithAggregatesInput = {
  AND?: Prisma.TrainingBlockScalarWhereWithAggregatesInput | Prisma.TrainingBlockScalarWhereWithAggregatesInput[]
  OR?: Prisma.TrainingBlockScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TrainingBlockScalarWhereWithAggregatesInput | Prisma.TrainingBlockScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TrainingBlock"> | string
  trainingPlanId?: Prisma.StringWithAggregatesFilter<"TrainingBlock"> | string
  order?: Prisma.IntWithAggregatesFilter<"TrainingBlock"> | number
  name?: Prisma.StringWithAggregatesFilter<"TrainingBlock"> | string
  type?: Prisma.StringWithAggregatesFilter<"TrainingBlock"> | string
  primaryFocus?: Prisma.StringWithAggregatesFilter<"TrainingBlock"> | string
  startDate?: Prisma.DateTimeWithAggregatesFilter<"TrainingBlock"> | Date | string
  durationWeeks?: Prisma.IntWithAggregatesFilter<"TrainingBlock"> | number
  recoveryWeekIndex?: Prisma.IntNullableWithAggregatesFilter<"TrainingBlock"> | number | null
  progressionLogic?: Prisma.StringNullableWithAggregatesFilter<"TrainingBlock"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TrainingBlock"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TrainingBlock"> | Date | string
  description?: Prisma.StringNullableWithAggregatesFilter<"TrainingBlock"> | string | null
}

export type TrainingBlockCreateInput = {
  id?: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
  plan: Prisma.TrainingPlanCreateNestedOneWithoutBlocksInput
  weeks?: Prisma.TrainingWeekCreateNestedManyWithoutBlockInput
}

export type TrainingBlockUncheckedCreateInput = {
  id?: string
  trainingPlanId: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
  weeks?: Prisma.TrainingWeekUncheckedCreateNestedManyWithoutBlockInput
}

export type TrainingBlockUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.TrainingPlanUpdateOneRequiredWithoutBlocksNestedInput
  weeks?: Prisma.TrainingWeekUpdateManyWithoutBlockNestedInput
}

export type TrainingBlockUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  trainingPlanId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  weeks?: Prisma.TrainingWeekUncheckedUpdateManyWithoutBlockNestedInput
}

export type TrainingBlockCreateManyInput = {
  id?: string
  trainingPlanId: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
}

export type TrainingBlockUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TrainingBlockUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  trainingPlanId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TrainingBlockListRelationFilter = {
  every?: Prisma.TrainingBlockWhereInput
  some?: Prisma.TrainingBlockWhereInput
  none?: Prisma.TrainingBlockWhereInput
}

export type TrainingBlockOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TrainingBlockCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainingPlanId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  primaryFocus?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrder
  progressionLogic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TrainingBlockAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrder
}

export type TrainingBlockMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainingPlanId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  primaryFocus?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrder
  progressionLogic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TrainingBlockMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  trainingPlanId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  primaryFocus?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrder
  progressionLogic?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type TrainingBlockSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
  durationWeeks?: Prisma.SortOrder
  recoveryWeekIndex?: Prisma.SortOrder
}

export type TrainingBlockScalarRelationFilter = {
  is?: Prisma.TrainingBlockWhereInput
  isNot?: Prisma.TrainingBlockWhereInput
}

export type TrainingBlockCreateNestedManyWithoutPlanInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput> | Prisma.TrainingBlockCreateWithoutPlanInput[] | Prisma.TrainingBlockUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutPlanInput | Prisma.TrainingBlockCreateOrConnectWithoutPlanInput[]
  createMany?: Prisma.TrainingBlockCreateManyPlanInputEnvelope
  connect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
}

export type TrainingBlockUncheckedCreateNestedManyWithoutPlanInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput> | Prisma.TrainingBlockCreateWithoutPlanInput[] | Prisma.TrainingBlockUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutPlanInput | Prisma.TrainingBlockCreateOrConnectWithoutPlanInput[]
  createMany?: Prisma.TrainingBlockCreateManyPlanInputEnvelope
  connect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
}

export type TrainingBlockUpdateManyWithoutPlanNestedInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput> | Prisma.TrainingBlockCreateWithoutPlanInput[] | Prisma.TrainingBlockUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutPlanInput | Prisma.TrainingBlockCreateOrConnectWithoutPlanInput[]
  upsert?: Prisma.TrainingBlockUpsertWithWhereUniqueWithoutPlanInput | Prisma.TrainingBlockUpsertWithWhereUniqueWithoutPlanInput[]
  createMany?: Prisma.TrainingBlockCreateManyPlanInputEnvelope
  set?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  disconnect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  delete?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  connect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  update?: Prisma.TrainingBlockUpdateWithWhereUniqueWithoutPlanInput | Prisma.TrainingBlockUpdateWithWhereUniqueWithoutPlanInput[]
  updateMany?: Prisma.TrainingBlockUpdateManyWithWhereWithoutPlanInput | Prisma.TrainingBlockUpdateManyWithWhereWithoutPlanInput[]
  deleteMany?: Prisma.TrainingBlockScalarWhereInput | Prisma.TrainingBlockScalarWhereInput[]
}

export type TrainingBlockUncheckedUpdateManyWithoutPlanNestedInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput> | Prisma.TrainingBlockCreateWithoutPlanInput[] | Prisma.TrainingBlockUncheckedCreateWithoutPlanInput[]
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutPlanInput | Prisma.TrainingBlockCreateOrConnectWithoutPlanInput[]
  upsert?: Prisma.TrainingBlockUpsertWithWhereUniqueWithoutPlanInput | Prisma.TrainingBlockUpsertWithWhereUniqueWithoutPlanInput[]
  createMany?: Prisma.TrainingBlockCreateManyPlanInputEnvelope
  set?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  disconnect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  delete?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  connect?: Prisma.TrainingBlockWhereUniqueInput | Prisma.TrainingBlockWhereUniqueInput[]
  update?: Prisma.TrainingBlockUpdateWithWhereUniqueWithoutPlanInput | Prisma.TrainingBlockUpdateWithWhereUniqueWithoutPlanInput[]
  updateMany?: Prisma.TrainingBlockUpdateManyWithWhereWithoutPlanInput | Prisma.TrainingBlockUpdateManyWithWhereWithoutPlanInput[]
  deleteMany?: Prisma.TrainingBlockScalarWhereInput | Prisma.TrainingBlockScalarWhereInput[]
}

export type TrainingBlockCreateNestedOneWithoutWeeksInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutWeeksInput, Prisma.TrainingBlockUncheckedCreateWithoutWeeksInput>
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutWeeksInput
  connect?: Prisma.TrainingBlockWhereUniqueInput
}

export type TrainingBlockUpdateOneRequiredWithoutWeeksNestedInput = {
  create?: Prisma.XOR<Prisma.TrainingBlockCreateWithoutWeeksInput, Prisma.TrainingBlockUncheckedCreateWithoutWeeksInput>
  connectOrCreate?: Prisma.TrainingBlockCreateOrConnectWithoutWeeksInput
  upsert?: Prisma.TrainingBlockUpsertWithoutWeeksInput
  connect?: Prisma.TrainingBlockWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TrainingBlockUpdateToOneWithWhereWithoutWeeksInput, Prisma.TrainingBlockUpdateWithoutWeeksInput>, Prisma.TrainingBlockUncheckedUpdateWithoutWeeksInput>
}

export type TrainingBlockCreateWithoutPlanInput = {
  id?: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
  weeks?: Prisma.TrainingWeekCreateNestedManyWithoutBlockInput
}

export type TrainingBlockUncheckedCreateWithoutPlanInput = {
  id?: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
  weeks?: Prisma.TrainingWeekUncheckedCreateNestedManyWithoutBlockInput
}

export type TrainingBlockCreateOrConnectWithoutPlanInput = {
  where: Prisma.TrainingBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput>
}

export type TrainingBlockCreateManyPlanInputEnvelope = {
  data: Prisma.TrainingBlockCreateManyPlanInput | Prisma.TrainingBlockCreateManyPlanInput[]
  skipDuplicates?: boolean
}

export type TrainingBlockUpsertWithWhereUniqueWithoutPlanInput = {
  where: Prisma.TrainingBlockWhereUniqueInput
  update: Prisma.XOR<Prisma.TrainingBlockUpdateWithoutPlanInput, Prisma.TrainingBlockUncheckedUpdateWithoutPlanInput>
  create: Prisma.XOR<Prisma.TrainingBlockCreateWithoutPlanInput, Prisma.TrainingBlockUncheckedCreateWithoutPlanInput>
}

export type TrainingBlockUpdateWithWhereUniqueWithoutPlanInput = {
  where: Prisma.TrainingBlockWhereUniqueInput
  data: Prisma.XOR<Prisma.TrainingBlockUpdateWithoutPlanInput, Prisma.TrainingBlockUncheckedUpdateWithoutPlanInput>
}

export type TrainingBlockUpdateManyWithWhereWithoutPlanInput = {
  where: Prisma.TrainingBlockScalarWhereInput
  data: Prisma.XOR<Prisma.TrainingBlockUpdateManyMutationInput, Prisma.TrainingBlockUncheckedUpdateManyWithoutPlanInput>
}

export type TrainingBlockScalarWhereInput = {
  AND?: Prisma.TrainingBlockScalarWhereInput | Prisma.TrainingBlockScalarWhereInput[]
  OR?: Prisma.TrainingBlockScalarWhereInput[]
  NOT?: Prisma.TrainingBlockScalarWhereInput | Prisma.TrainingBlockScalarWhereInput[]
  id?: Prisma.StringFilter<"TrainingBlock"> | string
  trainingPlanId?: Prisma.StringFilter<"TrainingBlock"> | string
  order?: Prisma.IntFilter<"TrainingBlock"> | number
  name?: Prisma.StringFilter<"TrainingBlock"> | string
  type?: Prisma.StringFilter<"TrainingBlock"> | string
  primaryFocus?: Prisma.StringFilter<"TrainingBlock"> | string
  startDate?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  durationWeeks?: Prisma.IntFilter<"TrainingBlock"> | number
  recoveryWeekIndex?: Prisma.IntNullableFilter<"TrainingBlock"> | number | null
  progressionLogic?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TrainingBlock"> | Date | string
  description?: Prisma.StringNullableFilter<"TrainingBlock"> | string | null
}

export type TrainingBlockCreateWithoutWeeksInput = {
  id?: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
  plan: Prisma.TrainingPlanCreateNestedOneWithoutBlocksInput
}

export type TrainingBlockUncheckedCreateWithoutWeeksInput = {
  id?: string
  trainingPlanId: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
}

export type TrainingBlockCreateOrConnectWithoutWeeksInput = {
  where: Prisma.TrainingBlockWhereUniqueInput
  create: Prisma.XOR<Prisma.TrainingBlockCreateWithoutWeeksInput, Prisma.TrainingBlockUncheckedCreateWithoutWeeksInput>
}

export type TrainingBlockUpsertWithoutWeeksInput = {
  update: Prisma.XOR<Prisma.TrainingBlockUpdateWithoutWeeksInput, Prisma.TrainingBlockUncheckedUpdateWithoutWeeksInput>
  create: Prisma.XOR<Prisma.TrainingBlockCreateWithoutWeeksInput, Prisma.TrainingBlockUncheckedCreateWithoutWeeksInput>
  where?: Prisma.TrainingBlockWhereInput
}

export type TrainingBlockUpdateToOneWithWhereWithoutWeeksInput = {
  where?: Prisma.TrainingBlockWhereInput
  data: Prisma.XOR<Prisma.TrainingBlockUpdateWithoutWeeksInput, Prisma.TrainingBlockUncheckedUpdateWithoutWeeksInput>
}

export type TrainingBlockUpdateWithoutWeeksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  plan?: Prisma.TrainingPlanUpdateOneRequiredWithoutBlocksNestedInput
}

export type TrainingBlockUncheckedUpdateWithoutWeeksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  trainingPlanId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TrainingBlockCreateManyPlanInput = {
  id?: string
  order: number
  name: string
  type: string
  primaryFocus: string
  startDate: Date | string
  durationWeeks: number
  recoveryWeekIndex?: number | null
  progressionLogic?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  description?: string | null
}

export type TrainingBlockUpdateWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  weeks?: Prisma.TrainingWeekUpdateManyWithoutBlockNestedInput
}

export type TrainingBlockUncheckedUpdateWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  weeks?: Prisma.TrainingWeekUncheckedUpdateManyWithoutBlockNestedInput
}

export type TrainingBlockUncheckedUpdateManyWithoutPlanInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  primaryFocus?: Prisma.StringFieldUpdateOperationsInput | string
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  durationWeeks?: Prisma.IntFieldUpdateOperationsInput | number
  recoveryWeekIndex?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  progressionLogic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TrainingBlockCountOutputType
 */

export type TrainingBlockCountOutputType = {
  weeks: number
}

export type TrainingBlockCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  weeks?: boolean | TrainingBlockCountOutputTypeCountWeeksArgs
}

/**
 * TrainingBlockCountOutputType without action
 */
export type TrainingBlockCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlockCountOutputType
   */
  select?: Prisma.TrainingBlockCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TrainingBlockCountOutputType without action
 */
export type TrainingBlockCountOutputTypeCountWeeksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TrainingWeekWhereInput
}


export type TrainingBlockSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainingPlanId?: boolean
  order?: boolean
  name?: boolean
  type?: boolean
  primaryFocus?: boolean
  startDate?: boolean
  durationWeeks?: boolean
  recoveryWeekIndex?: boolean
  progressionLogic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
  weeks?: boolean | Prisma.TrainingBlock$weeksArgs<ExtArgs>
  _count?: boolean | Prisma.TrainingBlockCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainingBlock"]>

export type TrainingBlockSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainingPlanId?: boolean
  order?: boolean
  name?: boolean
  type?: boolean
  primaryFocus?: boolean
  startDate?: boolean
  durationWeeks?: boolean
  recoveryWeekIndex?: boolean
  progressionLogic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainingBlock"]>

export type TrainingBlockSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  trainingPlanId?: boolean
  order?: boolean
  name?: boolean
  type?: boolean
  primaryFocus?: boolean
  startDate?: boolean
  durationWeeks?: boolean
  recoveryWeekIndex?: boolean
  progressionLogic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
}, ExtArgs["result"]["trainingBlock"]>

export type TrainingBlockSelectScalar = {
  id?: boolean
  trainingPlanId?: boolean
  order?: boolean
  name?: boolean
  type?: boolean
  primaryFocus?: boolean
  startDate?: boolean
  durationWeeks?: boolean
  recoveryWeekIndex?: boolean
  progressionLogic?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  description?: boolean
}

export type TrainingBlockOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "trainingPlanId" | "order" | "name" | "type" | "primaryFocus" | "startDate" | "durationWeeks" | "recoveryWeekIndex" | "progressionLogic" | "createdAt" | "updatedAt" | "description", ExtArgs["result"]["trainingBlock"]>
export type TrainingBlockInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
  weeks?: boolean | Prisma.TrainingBlock$weeksArgs<ExtArgs>
  _count?: boolean | Prisma.TrainingBlockCountOutputTypeDefaultArgs<ExtArgs>
}
export type TrainingBlockIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
}
export type TrainingBlockIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  plan?: boolean | Prisma.TrainingPlanDefaultArgs<ExtArgs>
}

export type $TrainingBlockPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TrainingBlock"
  objects: {
    plan: Prisma.$TrainingPlanPayload<ExtArgs>
    weeks: Prisma.$TrainingWeekPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    trainingPlanId: string
    order: number
    name: string
    type: string
    primaryFocus: string
    startDate: Date
    durationWeeks: number
    recoveryWeekIndex: number | null
    progressionLogic: string | null
    createdAt: Date
    updatedAt: Date
    description: string | null
  }, ExtArgs["result"]["trainingBlock"]>
  composites: {}
}

export type TrainingBlockGetPayload<S extends boolean | null | undefined | TrainingBlockDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload, S>

export type TrainingBlockCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TrainingBlockFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TrainingBlockCountAggregateInputType | true
  }

export interface TrainingBlockDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TrainingBlock'], meta: { name: 'TrainingBlock' } }
  /**
   * Find zero or one TrainingBlock that matches the filter.
   * @param {TrainingBlockFindUniqueArgs} args - Arguments to find a TrainingBlock
   * @example
   * // Get one TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TrainingBlockFindUniqueArgs>(args: Prisma.SelectSubset<T, TrainingBlockFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TrainingBlock that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TrainingBlockFindUniqueOrThrowArgs} args - Arguments to find a TrainingBlock
   * @example
   * // Get one TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TrainingBlockFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TrainingBlockFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrainingBlock that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockFindFirstArgs} args - Arguments to find a TrainingBlock
   * @example
   * // Get one TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TrainingBlockFindFirstArgs>(args?: Prisma.SelectSubset<T, TrainingBlockFindFirstArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TrainingBlock that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockFindFirstOrThrowArgs} args - Arguments to find a TrainingBlock
   * @example
   * // Get one TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TrainingBlockFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TrainingBlockFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TrainingBlocks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TrainingBlocks
   * const trainingBlocks = await prisma.trainingBlock.findMany()
   * 
   * // Get first 10 TrainingBlocks
   * const trainingBlocks = await prisma.trainingBlock.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const trainingBlockWithIdOnly = await prisma.trainingBlock.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TrainingBlockFindManyArgs>(args?: Prisma.SelectSubset<T, TrainingBlockFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TrainingBlock.
   * @param {TrainingBlockCreateArgs} args - Arguments to create a TrainingBlock.
   * @example
   * // Create one TrainingBlock
   * const TrainingBlock = await prisma.trainingBlock.create({
   *   data: {
   *     // ... data to create a TrainingBlock
   *   }
   * })
   * 
   */
  create<T extends TrainingBlockCreateArgs>(args: Prisma.SelectSubset<T, TrainingBlockCreateArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TrainingBlocks.
   * @param {TrainingBlockCreateManyArgs} args - Arguments to create many TrainingBlocks.
   * @example
   * // Create many TrainingBlocks
   * const trainingBlock = await prisma.trainingBlock.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TrainingBlockCreateManyArgs>(args?: Prisma.SelectSubset<T, TrainingBlockCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TrainingBlocks and returns the data saved in the database.
   * @param {TrainingBlockCreateManyAndReturnArgs} args - Arguments to create many TrainingBlocks.
   * @example
   * // Create many TrainingBlocks
   * const trainingBlock = await prisma.trainingBlock.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TrainingBlocks and only return the `id`
   * const trainingBlockWithIdOnly = await prisma.trainingBlock.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TrainingBlockCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TrainingBlockCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TrainingBlock.
   * @param {TrainingBlockDeleteArgs} args - Arguments to delete one TrainingBlock.
   * @example
   * // Delete one TrainingBlock
   * const TrainingBlock = await prisma.trainingBlock.delete({
   *   where: {
   *     // ... filter to delete one TrainingBlock
   *   }
   * })
   * 
   */
  delete<T extends TrainingBlockDeleteArgs>(args: Prisma.SelectSubset<T, TrainingBlockDeleteArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TrainingBlock.
   * @param {TrainingBlockUpdateArgs} args - Arguments to update one TrainingBlock.
   * @example
   * // Update one TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TrainingBlockUpdateArgs>(args: Prisma.SelectSubset<T, TrainingBlockUpdateArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TrainingBlocks.
   * @param {TrainingBlockDeleteManyArgs} args - Arguments to filter TrainingBlocks to delete.
   * @example
   * // Delete a few TrainingBlocks
   * const { count } = await prisma.trainingBlock.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TrainingBlockDeleteManyArgs>(args?: Prisma.SelectSubset<T, TrainingBlockDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrainingBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TrainingBlocks
   * const trainingBlock = await prisma.trainingBlock.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TrainingBlockUpdateManyArgs>(args: Prisma.SelectSubset<T, TrainingBlockUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TrainingBlocks and returns the data updated in the database.
   * @param {TrainingBlockUpdateManyAndReturnArgs} args - Arguments to update many TrainingBlocks.
   * @example
   * // Update many TrainingBlocks
   * const trainingBlock = await prisma.trainingBlock.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TrainingBlocks and only return the `id`
   * const trainingBlockWithIdOnly = await prisma.trainingBlock.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TrainingBlockUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TrainingBlockUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TrainingBlock.
   * @param {TrainingBlockUpsertArgs} args - Arguments to update or create a TrainingBlock.
   * @example
   * // Update or create a TrainingBlock
   * const trainingBlock = await prisma.trainingBlock.upsert({
   *   create: {
   *     // ... data to create a TrainingBlock
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TrainingBlock we want to update
   *   }
   * })
   */
  upsert<T extends TrainingBlockUpsertArgs>(args: Prisma.SelectSubset<T, TrainingBlockUpsertArgs<ExtArgs>>): Prisma.Prisma__TrainingBlockClient<runtime.Types.Result.GetResult<Prisma.$TrainingBlockPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TrainingBlocks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockCountArgs} args - Arguments to filter TrainingBlocks to count.
   * @example
   * // Count the number of TrainingBlocks
   * const count = await prisma.trainingBlock.count({
   *   where: {
   *     // ... the filter for the TrainingBlocks we want to count
   *   }
   * })
  **/
  count<T extends TrainingBlockCountArgs>(
    args?: Prisma.Subset<T, TrainingBlockCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TrainingBlockCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TrainingBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TrainingBlockAggregateArgs>(args: Prisma.Subset<T, TrainingBlockAggregateArgs>): Prisma.PrismaPromise<GetTrainingBlockAggregateType<T>>

  /**
   * Group by TrainingBlock.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TrainingBlockGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TrainingBlockGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TrainingBlockGroupByArgs['orderBy'] }
      : { orderBy?: TrainingBlockGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TrainingBlockGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTrainingBlockGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TrainingBlock model
 */
readonly fields: TrainingBlockFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TrainingBlock.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TrainingBlockClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  plan<T extends Prisma.TrainingPlanDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TrainingPlanDefaultArgs<ExtArgs>>): Prisma.Prisma__TrainingPlanClient<runtime.Types.Result.GetResult<Prisma.$TrainingPlanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  weeks<T extends Prisma.TrainingBlock$weeksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TrainingBlock$weeksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TrainingWeekPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TrainingBlock model
 */
export interface TrainingBlockFieldRefs {
  readonly id: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly trainingPlanId: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly order: Prisma.FieldRef<"TrainingBlock", 'Int'>
  readonly name: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly type: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly primaryFocus: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly startDate: Prisma.FieldRef<"TrainingBlock", 'DateTime'>
  readonly durationWeeks: Prisma.FieldRef<"TrainingBlock", 'Int'>
  readonly recoveryWeekIndex: Prisma.FieldRef<"TrainingBlock", 'Int'>
  readonly progressionLogic: Prisma.FieldRef<"TrainingBlock", 'String'>
  readonly createdAt: Prisma.FieldRef<"TrainingBlock", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TrainingBlock", 'DateTime'>
  readonly description: Prisma.FieldRef<"TrainingBlock", 'String'>
}
    

// Custom InputTypes
/**
 * TrainingBlock findUnique
 */
export type TrainingBlockFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter, which TrainingBlock to fetch.
   */
  where: Prisma.TrainingBlockWhereUniqueInput
}

/**
 * TrainingBlock findUniqueOrThrow
 */
export type TrainingBlockFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter, which TrainingBlock to fetch.
   */
  where: Prisma.TrainingBlockWhereUniqueInput
}

/**
 * TrainingBlock findFirst
 */
export type TrainingBlockFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter, which TrainingBlock to fetch.
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainingBlocks to fetch.
   */
  orderBy?: Prisma.TrainingBlockOrderByWithRelationInput | Prisma.TrainingBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrainingBlocks.
   */
  cursor?: Prisma.TrainingBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainingBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainingBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainingBlocks.
   */
  distinct?: Prisma.TrainingBlockScalarFieldEnum | Prisma.TrainingBlockScalarFieldEnum[]
}

/**
 * TrainingBlock findFirstOrThrow
 */
export type TrainingBlockFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter, which TrainingBlock to fetch.
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainingBlocks to fetch.
   */
  orderBy?: Prisma.TrainingBlockOrderByWithRelationInput | Prisma.TrainingBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TrainingBlocks.
   */
  cursor?: Prisma.TrainingBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainingBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainingBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainingBlocks.
   */
  distinct?: Prisma.TrainingBlockScalarFieldEnum | Prisma.TrainingBlockScalarFieldEnum[]
}

/**
 * TrainingBlock findMany
 */
export type TrainingBlockFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter, which TrainingBlocks to fetch.
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TrainingBlocks to fetch.
   */
  orderBy?: Prisma.TrainingBlockOrderByWithRelationInput | Prisma.TrainingBlockOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TrainingBlocks.
   */
  cursor?: Prisma.TrainingBlockWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TrainingBlocks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TrainingBlocks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TrainingBlocks.
   */
  distinct?: Prisma.TrainingBlockScalarFieldEnum | Prisma.TrainingBlockScalarFieldEnum[]
}

/**
 * TrainingBlock create
 */
export type TrainingBlockCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * The data needed to create a TrainingBlock.
   */
  data: Prisma.XOR<Prisma.TrainingBlockCreateInput, Prisma.TrainingBlockUncheckedCreateInput>
}

/**
 * TrainingBlock createMany
 */
export type TrainingBlockCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TrainingBlocks.
   */
  data: Prisma.TrainingBlockCreateManyInput | Prisma.TrainingBlockCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TrainingBlock createManyAndReturn
 */
export type TrainingBlockCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * The data used to create many TrainingBlocks.
   */
  data: Prisma.TrainingBlockCreateManyInput | Prisma.TrainingBlockCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TrainingBlock update
 */
export type TrainingBlockUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * The data needed to update a TrainingBlock.
   */
  data: Prisma.XOR<Prisma.TrainingBlockUpdateInput, Prisma.TrainingBlockUncheckedUpdateInput>
  /**
   * Choose, which TrainingBlock to update.
   */
  where: Prisma.TrainingBlockWhereUniqueInput
}

/**
 * TrainingBlock updateMany
 */
export type TrainingBlockUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TrainingBlocks.
   */
  data: Prisma.XOR<Prisma.TrainingBlockUpdateManyMutationInput, Prisma.TrainingBlockUncheckedUpdateManyInput>
  /**
   * Filter which TrainingBlocks to update
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * Limit how many TrainingBlocks to update.
   */
  limit?: number
}

/**
 * TrainingBlock updateManyAndReturn
 */
export type TrainingBlockUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * The data used to update TrainingBlocks.
   */
  data: Prisma.XOR<Prisma.TrainingBlockUpdateManyMutationInput, Prisma.TrainingBlockUncheckedUpdateManyInput>
  /**
   * Filter which TrainingBlocks to update
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * Limit how many TrainingBlocks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TrainingBlock upsert
 */
export type TrainingBlockUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * The filter to search for the TrainingBlock to update in case it exists.
   */
  where: Prisma.TrainingBlockWhereUniqueInput
  /**
   * In case the TrainingBlock found by the `where` argument doesn't exist, create a new TrainingBlock with this data.
   */
  create: Prisma.XOR<Prisma.TrainingBlockCreateInput, Prisma.TrainingBlockUncheckedCreateInput>
  /**
   * In case the TrainingBlock was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TrainingBlockUpdateInput, Prisma.TrainingBlockUncheckedUpdateInput>
}

/**
 * TrainingBlock delete
 */
export type TrainingBlockDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
  /**
   * Filter which TrainingBlock to delete.
   */
  where: Prisma.TrainingBlockWhereUniqueInput
}

/**
 * TrainingBlock deleteMany
 */
export type TrainingBlockDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TrainingBlocks to delete
   */
  where?: Prisma.TrainingBlockWhereInput
  /**
   * Limit how many TrainingBlocks to delete.
   */
  limit?: number
}

/**
 * TrainingBlock.weeks
 */
export type TrainingBlock$weeksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingWeek
   */
  select?: Prisma.TrainingWeekSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingWeek
   */
  omit?: Prisma.TrainingWeekOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingWeekInclude<ExtArgs> | null
  where?: Prisma.TrainingWeekWhereInput
  orderBy?: Prisma.TrainingWeekOrderByWithRelationInput | Prisma.TrainingWeekOrderByWithRelationInput[]
  cursor?: Prisma.TrainingWeekWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TrainingWeekScalarFieldEnum | Prisma.TrainingWeekScalarFieldEnum[]
}

/**
 * TrainingBlock without action
 */
export type TrainingBlockDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TrainingBlock
   */
  select?: Prisma.TrainingBlockSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TrainingBlock
   */
  omit?: Prisma.TrainingBlockOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TrainingBlockInclude<ExtArgs> | null
}
