/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from '@prisma/client/runtime/client'
import * as $Enums from './enums.js'
import type * as Prisma from './internal/prismaNamespace.js'

export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type IntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type FloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type JsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<JsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionStatus | Prisma.EnumSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel> | $Enums.SubscriptionStatus
}

export type EnumSubscriptionTierFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel> | $Enums.SubscriptionTier
}

export type EnumSubscriptionTierNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  notIn?:
    $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  not?:
    Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel> | $Enums.SubscriptionTier | null
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type EnumTeamVisibilityNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamVisibility | Prisma.EnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  in?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel> | $Enums.TeamVisibility | null
}

export type EnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type IntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type FloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type JsonNullableWithAggregatesFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonNullableWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonNullableWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedJsonNullableFilter<$PrismaModel>
  _max?: Prisma.NestedJsonNullableFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionStatus | Prisma.EnumSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel>
}

export type EnumSubscriptionTierWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumSubscriptionTierWithAggregatesFilter<$PrismaModel> | $Enums.SubscriptionTier
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel>
}

export type EnumSubscriptionTierNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  notIn?:
    $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  not?:
    | Prisma.NestedEnumSubscriptionTierNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionTier
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumTeamVisibilityNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamVisibility | Prisma.EnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  in?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  not?:
    | Prisma.NestedEnumTeamVisibilityNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.TeamVisibility
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel>
}

export type EnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type EnumReferralStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReferralStatus | Prisma.EnumReferralStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel> | $Enums.ReferralStatus
}

export type EnumReferralStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReferralStatus | Prisma.EnumReferralStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumReferralStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReferralStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel>
}

export type BoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null
}

export type BoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>
}

export type BytesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  notIn?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBytesFilter<$PrismaModel> | runtime.Bytes
}

export type BytesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  notIn?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBytesWithAggregatesFilter<$PrismaModel> | runtime.Bytes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBytesFilter<$PrismaModel>
  _max?: Prisma.NestedBytesFilter<$PrismaModel>
}

export type FloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type FloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type JsonFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<JsonFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonFilterBase<$PrismaModel>>, 'path'>>

export type JsonFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type JsonWithAggregatesFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<JsonWithAggregatesFilterBase<$PrismaModel>>,
        Exclude<keyof Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<JsonWithAggregatesFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedJsonFilter<$PrismaModel>
  _max?: Prisma.NestedJsonFilter<$PrismaModel>
}

export type EnumUserMemoryScopeFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryScope | Prisma.EnumUserMemoryScopeFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel> | $Enums.UserMemoryScope
}

export type EnumUserMemoryCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryCategory | Prisma.EnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel> | $Enums.UserMemoryCategory
}

export type EnumUserMemorySourceFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemorySource | Prisma.EnumUserMemorySourceFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel> | $Enums.UserMemorySource
}

export type EnumUserMemoryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryStatus | Prisma.EnumUserMemoryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel> | $Enums.UserMemoryStatus
}

export type EnumUserMemoryScopeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryScope | Prisma.EnumUserMemoryScopeFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryScopeWithAggregatesFilter<$PrismaModel> | $Enums.UserMemoryScope
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel>
}

export type EnumUserMemoryCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryCategory | Prisma.EnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumUserMemoryCategoryWithAggregatesFilter<$PrismaModel>
    | $Enums.UserMemoryCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel>
}

export type EnumUserMemorySourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemorySource | Prisma.EnumUserMemorySourceFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumUserMemorySourceWithAggregatesFilter<$PrismaModel> | $Enums.UserMemorySource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel>
}

export type EnumUserMemoryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryStatus | Prisma.EnumUserMemoryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumUserMemoryStatusWithAggregatesFilter<$PrismaModel> | $Enums.UserMemoryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel>
}

export type EnumSubscriptionProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel>
  in?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel> | $Enums.SubscriptionProvider
}

export type EnumProviderSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ProviderSubscriptionStatus
    | Prisma.EnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  in?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
    | $Enums.ProviderSubscriptionStatus
}

export type EnumSubscriptionEnvironmentFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionEnvironment | Prisma.EnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  in?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel> | $Enums.SubscriptionEnvironment
}

export type EnumSubscriptionProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel>
  in?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionProviderWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel>
}

export type EnumProviderSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ProviderSubscriptionStatus
    | Prisma.EnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  in?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumProviderSubscriptionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.ProviderSubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
}

export type EnumSubscriptionEnvironmentWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionEnvironment | Prisma.EnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  in?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionEnvironmentWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionEnvironment
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel>
}

export type EnumSubscriptionProviderNullableFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel> | null
  in?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  notIn?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  not?:
    | Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
    | null
}

export type EnumSubscriptionProviderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel> | null
  in?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  notIn?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  not?:
    | Prisma.NestedEnumSubscriptionProviderNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
}

export type EnumBugStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.BugStatus | Prisma.EnumBugStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBugStatusFilter<$PrismaModel> | $Enums.BugStatus
}

export type EnumBugStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BugStatus | Prisma.EnumBugStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBugStatusWithAggregatesFilter<$PrismaModel> | $Enums.BugStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBugStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBugStatusFilter<$PrismaModel>
}

export type EnumCommentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommentType | Prisma.EnumCommentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel> | $Enums.CommentType
}

export type EnumCommentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommentType | Prisma.EnumCommentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommentTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel>
}

export type EnumJourneyEventTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventType | Prisma.EnumJourneyEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel> | $Enums.JourneyEventType
}

export type EnumJourneyEventCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventCategory | Prisma.EnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  in?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel> | $Enums.JourneyEventCategory
}

export type EnumJourneyEventTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventType | Prisma.EnumJourneyEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumJourneyEventTypeWithAggregatesFilter<$PrismaModel> | $Enums.JourneyEventType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel>
}

export type EnumJourneyEventCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventCategory | Prisma.EnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  in?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumJourneyEventCategoryWithAggregatesFilter<$PrismaModel>
    | $Enums.JourneyEventCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel>
}

export type EnumEmailPreferenceChannelFilter<$PrismaModel = never> = {
  equals?:
    $Enums.EmailPreferenceChannel | Prisma.EnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  in?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel> | $Enums.EmailPreferenceChannel
}

export type EnumEmailPreferenceChannelWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.EmailPreferenceChannel | Prisma.EnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  in?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumEmailPreferenceChannelWithAggregatesFilter<$PrismaModel>
    | $Enums.EmailPreferenceChannel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel>
}

export type EnumEmailProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailProvider | Prisma.EnumEmailProviderFieldRefInput<$PrismaModel>
  in?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel> | $Enums.EmailProvider
}

export type EnumEmailAudienceFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailAudience | Prisma.EnumEmailAudienceFieldRefInput<$PrismaModel>
  in?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel> | $Enums.EmailAudience
}

export type EnumEmailDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailDeliveryStatus | Prisma.EnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel> | $Enums.EmailDeliveryStatus
}

export type EnumEmailProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailProvider | Prisma.EnumEmailProviderFieldRefInput<$PrismaModel>
  in?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailProviderWithAggregatesFilter<$PrismaModel> | $Enums.EmailProvider
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel>
}

export type EnumEmailAudienceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailAudience | Prisma.EnumEmailAudienceFieldRefInput<$PrismaModel>
  in?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailAudienceWithAggregatesFilter<$PrismaModel> | $Enums.EmailAudience
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel>
}

export type EnumEmailDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailDeliveryStatus | Prisma.EnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumEmailDeliveryStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.EmailDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel>
}

export type EnumTeamRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamRole | Prisma.EnumTeamRoleFieldRefInput<$PrismaModel>
  in?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel> | $Enums.TeamRole
}

export type EnumTeamRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamRole | Prisma.EnumTeamRoleFieldRefInput<$PrismaModel>
  in?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTeamRoleWithAggregatesFilter<$PrismaModel> | $Enums.TeamRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedFloatNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableFilter<$PrismaModel> | number | null
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionStatus | Prisma.EnumSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel> | $Enums.SubscriptionStatus
}

export type NestedEnumSubscriptionTierFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel> | $Enums.SubscriptionTier
}

export type NestedEnumSubscriptionTierNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  notIn?:
    $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  not?:
    Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel> | $Enums.SubscriptionTier | null
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumTeamVisibilityNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamVisibility | Prisma.EnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  in?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel> | $Enums.TeamVisibility | null
}

export type NestedEnumRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleFilter<$PrismaModel> | $Enums.Role
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedIntNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _max?: Prisma.NestedIntNullableFilter<$PrismaModel>
}

export type NestedFloatNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatNullableWithAggregatesFilter<$PrismaModel> | number | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _min?: Prisma.NestedFloatNullableFilter<$PrismaModel>
  _max?: Prisma.NestedFloatNullableFilter<$PrismaModel>
}

export type NestedJsonNullableFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<NestedJsonNullableFilterBase<$PrismaModel>>,
        Exclude<keyof Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<NestedJsonNullableFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<NestedJsonNullableFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonNullableFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionStatus | Prisma.EnumSubscriptionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionStatus[] | Prisma.ListEnumSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionStatusFilter<$PrismaModel>
}

export type NestedEnumSubscriptionTierWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel>
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  notIn?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumSubscriptionTierWithAggregatesFilter<$PrismaModel> | $Enums.SubscriptionTier
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionTierFilter<$PrismaModel>
}

export type NestedEnumSubscriptionTierNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionTier | Prisma.EnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  in?: $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  notIn?:
    $Enums.SubscriptionTier[] | Prisma.ListEnumSubscriptionTierFieldRefInput<$PrismaModel> | null
  not?:
    | Prisma.NestedEnumSubscriptionTierNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionTier
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionTierNullableFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumTeamVisibilityNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamVisibility | Prisma.EnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  in?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.TeamVisibility[] | Prisma.ListEnumTeamVisibilityFieldRefInput<$PrismaModel> | null
  not?:
    | Prisma.NestedEnumTeamVisibilityNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.TeamVisibility
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTeamVisibilityNullableFilter<$PrismaModel>
}

export type NestedEnumRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.Role | Prisma.EnumRoleFieldRefInput<$PrismaModel>
  in?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.Role[] | Prisma.ListEnumRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumRoleWithAggregatesFilter<$PrismaModel> | $Enums.Role
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumRoleFilter<$PrismaModel>
}

export type NestedEnumReferralStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ReferralStatus | Prisma.EnumReferralStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel> | $Enums.ReferralStatus
}

export type NestedEnumReferralStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ReferralStatus | Prisma.EnumReferralStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ReferralStatus[] | Prisma.ListEnumReferralStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumReferralStatusWithAggregatesFilter<$PrismaModel> | $Enums.ReferralStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumReferralStatusFilter<$PrismaModel>
}

export type NestedBoolNullableFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableFilter<$PrismaModel> | boolean | null
}

export type NestedBoolNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedBoolNullableWithAggregatesFilter<$PrismaModel> | boolean | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedBoolNullableFilter<$PrismaModel>
  _max?: Prisma.NestedBoolNullableFilter<$PrismaModel>
}

export type NestedBytesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  notIn?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBytesFilter<$PrismaModel> | runtime.Bytes
}

export type NestedBytesWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Bytes | Prisma.BytesFieldRefInput<$PrismaModel>
  in?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  notIn?: runtime.Bytes[] | Prisma.ListBytesFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBytesWithAggregatesFilter<$PrismaModel> | runtime.Bytes
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBytesFilter<$PrismaModel>
  _max?: Prisma.NestedBytesFilter<$PrismaModel>
}

export type NestedFloatWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedFloatFilter<$PrismaModel>
  _min?: Prisma.NestedFloatFilter<$PrismaModel>
  _max?: Prisma.NestedFloatFilter<$PrismaModel>
}

export type NestedJsonFilter<$PrismaModel = never> =
  | Prisma.PatchUndefined<
      Prisma.Either<
        Required<NestedJsonFilterBase<$PrismaModel>>,
        Exclude<keyof Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>
      >,
      Required<NestedJsonFilterBase<$PrismaModel>>
    >
  | Prisma.OptionalFlat<Omit<Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonFilterBase<$PrismaModel = never> = {
  equals?:
    runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedEnumUserMemoryScopeFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryScope | Prisma.EnumUserMemoryScopeFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel> | $Enums.UserMemoryScope
}

export type NestedEnumUserMemoryCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryCategory | Prisma.EnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel> | $Enums.UserMemoryCategory
}

export type NestedEnumUserMemorySourceFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemorySource | Prisma.EnumUserMemorySourceFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel> | $Enums.UserMemorySource
}

export type NestedEnumUserMemoryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryStatus | Prisma.EnumUserMemoryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel> | $Enums.UserMemoryStatus
}

export type NestedEnumUserMemoryScopeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryScope | Prisma.EnumUserMemoryScopeFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryScope[] | Prisma.ListEnumUserMemoryScopeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumUserMemoryScopeWithAggregatesFilter<$PrismaModel> | $Enums.UserMemoryScope
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryScopeFilter<$PrismaModel>
}

export type NestedEnumUserMemoryCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryCategory | Prisma.EnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryCategory[] | Prisma.ListEnumUserMemoryCategoryFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumUserMemoryCategoryWithAggregatesFilter<$PrismaModel>
    | $Enums.UserMemoryCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryCategoryFilter<$PrismaModel>
}

export type NestedEnumUserMemorySourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemorySource | Prisma.EnumUserMemorySourceFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemorySource[] | Prisma.ListEnumUserMemorySourceFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumUserMemorySourceWithAggregatesFilter<$PrismaModel> | $Enums.UserMemorySource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemorySourceFilter<$PrismaModel>
}

export type NestedEnumUserMemoryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.UserMemoryStatus | Prisma.EnumUserMemoryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.UserMemoryStatus[] | Prisma.ListEnumUserMemoryStatusFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumUserMemoryStatusWithAggregatesFilter<$PrismaModel> | $Enums.UserMemoryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumUserMemoryStatusFilter<$PrismaModel>
}

export type NestedEnumSubscriptionProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel>
  in?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel> | $Enums.SubscriptionProvider
}

export type NestedEnumProviderSubscriptionStatusFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ProviderSubscriptionStatus
    | Prisma.EnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  in?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
    | $Enums.ProviderSubscriptionStatus
}

export type NestedEnumSubscriptionEnvironmentFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionEnvironment | Prisma.EnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  in?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel> | $Enums.SubscriptionEnvironment
}

export type NestedEnumSubscriptionProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel>
  in?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.SubscriptionProvider[] | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionProviderWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionProviderFilter<$PrismaModel>
}

export type NestedEnumProviderSubscriptionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    | $Enums.ProviderSubscriptionStatus
    | Prisma.EnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  in?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.ProviderSubscriptionStatus[]
    | Prisma.ListEnumProviderSubscriptionStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumProviderSubscriptionStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.ProviderSubscriptionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProviderSubscriptionStatusFilter<$PrismaModel>
}

export type NestedEnumSubscriptionEnvironmentWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionEnvironment | Prisma.EnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  in?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.SubscriptionEnvironment[]
    | Prisma.ListEnumSubscriptionEnvironmentFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumSubscriptionEnvironmentWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionEnvironment
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionEnvironmentFilter<$PrismaModel>
}

export type NestedEnumSubscriptionProviderNullableFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel> | null
  in?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  notIn?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  not?:
    | Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
    | null
}

export type NestedEnumSubscriptionProviderNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.SubscriptionProvider | Prisma.EnumSubscriptionProviderFieldRefInput<$PrismaModel> | null
  in?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  notIn?:
    | $Enums.SubscriptionProvider[]
    | Prisma.ListEnumSubscriptionProviderFieldRefInput<$PrismaModel>
    | null
  not?:
    | Prisma.NestedEnumSubscriptionProviderNullableWithAggregatesFilter<$PrismaModel>
    | $Enums.SubscriptionProvider
    | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSubscriptionProviderNullableFilter<$PrismaModel>
}

export type NestedEnumBugStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.BugStatus | Prisma.EnumBugStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBugStatusFilter<$PrismaModel> | $Enums.BugStatus
}

export type NestedEnumBugStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.BugStatus | Prisma.EnumBugStatusFieldRefInput<$PrismaModel>
  in?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.BugStatus[] | Prisma.ListEnumBugStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumBugStatusWithAggregatesFilter<$PrismaModel> | $Enums.BugStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumBugStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumBugStatusFilter<$PrismaModel>
}

export type NestedEnumCommentTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommentType | Prisma.EnumCommentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel> | $Enums.CommentType
}

export type NestedEnumCommentTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommentType | Prisma.EnumCommentTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommentType[] | Prisma.ListEnumCommentTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommentTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommentType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommentTypeFilter<$PrismaModel>
}

export type NestedEnumJourneyEventTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventType | Prisma.EnumJourneyEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel> | $Enums.JourneyEventType
}

export type NestedEnumJourneyEventCategoryFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventCategory | Prisma.EnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  in?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel> | $Enums.JourneyEventCategory
}

export type NestedEnumJourneyEventTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventType | Prisma.EnumJourneyEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.JourneyEventType[] | Prisma.ListEnumJourneyEventTypeFieldRefInput<$PrismaModel>
  not?:
    Prisma.NestedEnumJourneyEventTypeWithAggregatesFilter<$PrismaModel> | $Enums.JourneyEventType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumJourneyEventTypeFilter<$PrismaModel>
}

export type NestedEnumJourneyEventCategoryWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.JourneyEventCategory | Prisma.EnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  in?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.JourneyEventCategory[] | Prisma.ListEnumJourneyEventCategoryFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumJourneyEventCategoryWithAggregatesFilter<$PrismaModel>
    | $Enums.JourneyEventCategory
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel>
  _max?: Prisma.NestedEnumJourneyEventCategoryFilter<$PrismaModel>
}

export type NestedEnumEmailPreferenceChannelFilter<$PrismaModel = never> = {
  equals?:
    $Enums.EmailPreferenceChannel | Prisma.EnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  in?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel> | $Enums.EmailPreferenceChannel
}

export type NestedEnumEmailPreferenceChannelWithAggregatesFilter<$PrismaModel = never> = {
  equals?:
    $Enums.EmailPreferenceChannel | Prisma.EnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  in?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  notIn?:
    | $Enums.EmailPreferenceChannel[]
    | Prisma.ListEnumEmailPreferenceChannelFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumEmailPreferenceChannelWithAggregatesFilter<$PrismaModel>
    | $Enums.EmailPreferenceChannel
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailPreferenceChannelFilter<$PrismaModel>
}

export type NestedEnumEmailProviderFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailProvider | Prisma.EnumEmailProviderFieldRefInput<$PrismaModel>
  in?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel> | $Enums.EmailProvider
}

export type NestedEnumEmailAudienceFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailAudience | Prisma.EnumEmailAudienceFieldRefInput<$PrismaModel>
  in?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel> | $Enums.EmailAudience
}

export type NestedEnumEmailDeliveryStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailDeliveryStatus | Prisma.EnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel> | $Enums.EmailDeliveryStatus
}

export type NestedEnumEmailProviderWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailProvider | Prisma.EnumEmailProviderFieldRefInput<$PrismaModel>
  in?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailProvider[] | Prisma.ListEnumEmailProviderFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailProviderWithAggregatesFilter<$PrismaModel> | $Enums.EmailProvider
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailProviderFilter<$PrismaModel>
}

export type NestedEnumEmailAudienceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailAudience | Prisma.EnumEmailAudienceFieldRefInput<$PrismaModel>
  in?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  notIn?: $Enums.EmailAudience[] | Prisma.ListEnumEmailAudienceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumEmailAudienceWithAggregatesFilter<$PrismaModel> | $Enums.EmailAudience
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailAudienceFilter<$PrismaModel>
}

export type NestedEnumEmailDeliveryStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.EmailDeliveryStatus | Prisma.EnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  in?: $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  notIn?:
    $Enums.EmailDeliveryStatus[] | Prisma.ListEnumEmailDeliveryStatusFieldRefInput<$PrismaModel>
  not?:
    | Prisma.NestedEnumEmailDeliveryStatusWithAggregatesFilter<$PrismaModel>
    | $Enums.EmailDeliveryStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumEmailDeliveryStatusFilter<$PrismaModel>
}

export type NestedEnumTeamRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamRole | Prisma.EnumTeamRoleFieldRefInput<$PrismaModel>
  in?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel> | $Enums.TeamRole
}

export type NestedEnumTeamRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TeamRole | Prisma.EnumTeamRoleFieldRefInput<$PrismaModel>
  in?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.TeamRole[] | Prisma.ListEnumTeamRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTeamRoleWithAggregatesFilter<$PrismaModel> | $Enums.TeamRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTeamRoleFilter<$PrismaModel>
}
