/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ScheduledTaskConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model ScheduledTaskConfig
 *
 */
export type ScheduledTaskConfigModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ScheduledTaskConfigPayload>

export type AggregateScheduledTaskConfig = {
  _count: ScheduledTaskConfigCountAggregateOutputType | null
  _min: ScheduledTaskConfigMinAggregateOutputType | null
  _max: ScheduledTaskConfigMaxAggregateOutputType | null
}

export type ScheduledTaskConfigMinAggregateOutputType = {
  id: string | null
  taskName: string | null
  displayName: string | null
  cronExpression: string | null
  enabled: boolean | null
  lastRunAt: Date | null
  lastStatus: string | null
  lastError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledTaskConfigMaxAggregateOutputType = {
  id: string | null
  taskName: string | null
  displayName: string | null
  cronExpression: string | null
  enabled: boolean | null
  lastRunAt: Date | null
  lastStatus: string | null
  lastError: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ScheduledTaskConfigCountAggregateOutputType = {
  id: number
  taskName: number
  displayName: number
  cronExpression: number
  enabled: number
  lastRunAt: number
  lastStatus: number
  lastError: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type ScheduledTaskConfigMinAggregateInputType = {
  id?: true
  taskName?: true
  displayName?: true
  cronExpression?: true
  enabled?: true
  lastRunAt?: true
  lastStatus?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledTaskConfigMaxAggregateInputType = {
  id?: true
  taskName?: true
  displayName?: true
  cronExpression?: true
  enabled?: true
  lastRunAt?: true
  lastStatus?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
}

export type ScheduledTaskConfigCountAggregateInputType = {
  id?: true
  taskName?: true
  displayName?: true
  cronExpression?: true
  enabled?: true
  lastRunAt?: true
  lastStatus?: true
  lastError?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ScheduledTaskConfigAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which ScheduledTaskConfig to aggregate.
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ScheduledTaskConfigs to fetch.
   */
  orderBy?:
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ScheduledTaskConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ScheduledTaskConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ScheduledTaskConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ScheduledTaskConfigs
   **/
  _count?: true | ScheduledTaskConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ScheduledTaskConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ScheduledTaskConfigMaxAggregateInputType
}

export type GetScheduledTaskConfigAggregateType<T extends ScheduledTaskConfigAggregateArgs> = {
  [P in keyof T & keyof AggregateScheduledTaskConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateScheduledTaskConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateScheduledTaskConfig[P]>
}

export type ScheduledTaskConfigGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  where?: Prisma.ScheduledTaskConfigWhereInput
  orderBy?:
    | Prisma.ScheduledTaskConfigOrderByWithAggregationInput
    | Prisma.ScheduledTaskConfigOrderByWithAggregationInput[]
  by: Prisma.ScheduledTaskConfigScalarFieldEnum[] | Prisma.ScheduledTaskConfigScalarFieldEnum
  having?: Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ScheduledTaskConfigCountAggregateInputType | true
  _min?: ScheduledTaskConfigMinAggregateInputType
  _max?: ScheduledTaskConfigMaxAggregateInputType
}

export type ScheduledTaskConfigGroupByOutputType = {
  id: string
  taskName: string
  displayName: string
  cronExpression: string
  enabled: boolean
  lastRunAt: Date | null
  lastStatus: string | null
  lastError: string | null
  createdAt: Date
  updatedAt: Date
  _count: ScheduledTaskConfigCountAggregateOutputType | null
  _min: ScheduledTaskConfigMinAggregateOutputType | null
  _max: ScheduledTaskConfigMaxAggregateOutputType | null
}

export type GetScheduledTaskConfigGroupByPayload<T extends ScheduledTaskConfigGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<ScheduledTaskConfigGroupByOutputType, T['by']> & {
        [P in keyof T & keyof ScheduledTaskConfigGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ScheduledTaskConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ScheduledTaskConfigGroupByOutputType[P]>
      }
    >
  >

export type ScheduledTaskConfigWhereInput = {
  AND?: Prisma.ScheduledTaskConfigWhereInput | Prisma.ScheduledTaskConfigWhereInput[]
  OR?: Prisma.ScheduledTaskConfigWhereInput[]
  NOT?: Prisma.ScheduledTaskConfigWhereInput | Prisma.ScheduledTaskConfigWhereInput[]
  id?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
  taskName?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
  displayName?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
  cronExpression?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
  enabled?: Prisma.BoolFilter<'ScheduledTaskConfig'> | boolean
  lastRunAt?: Prisma.DateTimeNullableFilter<'ScheduledTaskConfig'> | Date | string | null
  lastStatus?: Prisma.StringNullableFilter<'ScheduledTaskConfig'> | string | null
  lastError?: Prisma.StringNullableFilter<'ScheduledTaskConfig'> | string | null
  createdAt?: Prisma.DateTimeFilter<'ScheduledTaskConfig'> | Date | string
  updatedAt?: Prisma.DateTimeFilter<'ScheduledTaskConfig'> | Date | string
}

export type ScheduledTaskConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  taskName?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  cronExpression?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledTaskConfigWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    taskName?: string
    AND?: Prisma.ScheduledTaskConfigWhereInput | Prisma.ScheduledTaskConfigWhereInput[]
    OR?: Prisma.ScheduledTaskConfigWhereInput[]
    NOT?: Prisma.ScheduledTaskConfigWhereInput | Prisma.ScheduledTaskConfigWhereInput[]
    displayName?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
    cronExpression?: Prisma.StringFilter<'ScheduledTaskConfig'> | string
    enabled?: Prisma.BoolFilter<'ScheduledTaskConfig'> | boolean
    lastRunAt?: Prisma.DateTimeNullableFilter<'ScheduledTaskConfig'> | Date | string | null
    lastStatus?: Prisma.StringNullableFilter<'ScheduledTaskConfig'> | string | null
    lastError?: Prisma.StringNullableFilter<'ScheduledTaskConfig'> | string | null
    createdAt?: Prisma.DateTimeFilter<'ScheduledTaskConfig'> | Date | string
    updatedAt?: Prisma.DateTimeFilter<'ScheduledTaskConfig'> | Date | string
  },
  'id' | 'taskName'
>

export type ScheduledTaskConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  taskName?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  cronExpression?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  lastStatus?: Prisma.SortOrderInput | Prisma.SortOrder
  lastError?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ScheduledTaskConfigCountOrderByAggregateInput
  _max?: Prisma.ScheduledTaskConfigMaxOrderByAggregateInput
  _min?: Prisma.ScheduledTaskConfigMinOrderByAggregateInput
}

export type ScheduledTaskConfigScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput
    | Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput
    | Prisma.ScheduledTaskConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'ScheduledTaskConfig'> | string
  taskName?: Prisma.StringWithAggregatesFilter<'ScheduledTaskConfig'> | string
  displayName?: Prisma.StringWithAggregatesFilter<'ScheduledTaskConfig'> | string
  cronExpression?: Prisma.StringWithAggregatesFilter<'ScheduledTaskConfig'> | string
  enabled?: Prisma.BoolWithAggregatesFilter<'ScheduledTaskConfig'> | boolean
  lastRunAt?:
    Prisma.DateTimeNullableWithAggregatesFilter<'ScheduledTaskConfig'> | Date | string | null
  lastStatus?: Prisma.StringNullableWithAggregatesFilter<'ScheduledTaskConfig'> | string | null
  lastError?: Prisma.StringNullableWithAggregatesFilter<'ScheduledTaskConfig'> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<'ScheduledTaskConfig'> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<'ScheduledTaskConfig'> | Date | string
}

export type ScheduledTaskConfigCreateInput = {
  id?: string
  taskName: string
  displayName: string
  cronExpression: string
  enabled?: boolean
  lastRunAt?: Date | string | null
  lastStatus?: string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledTaskConfigUncheckedCreateInput = {
  id?: string
  taskName: string
  displayName: string
  cronExpression: string
  enabled?: boolean
  lastRunAt?: Date | string | null
  lastStatus?: string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledTaskConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskName?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  cronExpression?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledTaskConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskName?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  cronExpression?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledTaskConfigCreateManyInput = {
  id?: string
  taskName: string
  displayName: string
  cronExpression: string
  enabled?: boolean
  lastRunAt?: Date | string | null
  lastStatus?: string | null
  lastError?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ScheduledTaskConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskName?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  cronExpression?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledTaskConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  taskName?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  cronExpression?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  lastStatus?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lastError?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ScheduledTaskConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskName?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  cronExpression?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledTaskConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskName?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  cronExpression?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledTaskConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  taskName?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  cronExpression?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  lastStatus?: Prisma.SortOrder
  lastError?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ScheduledTaskConfigSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    taskName?: boolean
    displayName?: boolean
    cronExpression?: boolean
    enabled?: boolean
    lastRunAt?: boolean
    lastStatus?: boolean
    lastError?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  },
  ExtArgs['result']['scheduledTaskConfig']
>

export type ScheduledTaskConfigSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    taskName?: boolean
    displayName?: boolean
    cronExpression?: boolean
    enabled?: boolean
    lastRunAt?: boolean
    lastStatus?: boolean
    lastError?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  },
  ExtArgs['result']['scheduledTaskConfig']
>

export type ScheduledTaskConfigSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    taskName?: boolean
    displayName?: boolean
    cronExpression?: boolean
    enabled?: boolean
    lastRunAt?: boolean
    lastStatus?: boolean
    lastError?: boolean
    createdAt?: boolean
    updatedAt?: boolean
  },
  ExtArgs['result']['scheduledTaskConfig']
>

export type ScheduledTaskConfigSelectScalar = {
  id?: boolean
  taskName?: boolean
  displayName?: boolean
  cronExpression?: boolean
  enabled?: boolean
  lastRunAt?: boolean
  lastStatus?: boolean
  lastError?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ScheduledTaskConfigOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'taskName'
  | 'displayName'
  | 'cronExpression'
  | 'enabled'
  | 'lastRunAt'
  | 'lastStatus'
  | 'lastError'
  | 'createdAt'
  | 'updatedAt',
  ExtArgs['result']['scheduledTaskConfig']
>

export type $ScheduledTaskConfigPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  name: 'ScheduledTaskConfig'
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      taskName: string
      displayName: string
      cronExpression: string
      enabled: boolean
      lastRunAt: Date | null
      lastStatus: string | null
      lastError: string | null
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs['result']['scheduledTaskConfig']
  >
  composites: {}
}

export type ScheduledTaskConfigGetPayload<
  S extends boolean | null | undefined | ScheduledTaskConfigDefaultArgs
> = runtime.Types.Result.GetResult<Prisma.$ScheduledTaskConfigPayload, S>

export type ScheduledTaskConfigCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = Omit<ScheduledTaskConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ScheduledTaskConfigCountAggregateInputType | true
}

export interface ScheduledTaskConfigDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ScheduledTaskConfig']
    meta: { name: 'ScheduledTaskConfig' }
  }
  /**
   * Find zero or one ScheduledTaskConfig that matches the filter.
   * @param {ScheduledTaskConfigFindUniqueArgs} args - Arguments to find a ScheduledTaskConfig
   * @example
   * // Get one ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ScheduledTaskConfigFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one ScheduledTaskConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ScheduledTaskConfigFindUniqueOrThrowArgs} args - Arguments to find a ScheduledTaskConfig
   * @example
   * // Get one ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ScheduledTaskConfigFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first ScheduledTaskConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigFindFirstArgs} args - Arguments to find a ScheduledTaskConfig
   * @example
   * // Get one ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ScheduledTaskConfigFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first ScheduledTaskConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigFindFirstOrThrowArgs} args - Arguments to find a ScheduledTaskConfig
   * @example
   * // Get one ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ScheduledTaskConfigFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more ScheduledTaskConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ScheduledTaskConfigs
   * const scheduledTaskConfigs = await prisma.scheduledTaskConfig.findMany()
   *
   * // Get first 10 ScheduledTaskConfigs
   * const scheduledTaskConfigs = await prisma.scheduledTaskConfig.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const scheduledTaskConfigWithIdOnly = await prisma.scheduledTaskConfig.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ScheduledTaskConfigFindManyArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a ScheduledTaskConfig.
   * @param {ScheduledTaskConfigCreateArgs} args - Arguments to create a ScheduledTaskConfig.
   * @example
   * // Create one ScheduledTaskConfig
   * const ScheduledTaskConfig = await prisma.scheduledTaskConfig.create({
   *   data: {
   *     // ... data to create a ScheduledTaskConfig
   *   }
   * })
   *
   */
  create<T extends ScheduledTaskConfigCreateArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigCreateArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many ScheduledTaskConfigs.
   * @param {ScheduledTaskConfigCreateManyArgs} args - Arguments to create many ScheduledTaskConfigs.
   * @example
   * // Create many ScheduledTaskConfigs
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ScheduledTaskConfigCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ScheduledTaskConfigs and returns the data saved in the database.
   * @param {ScheduledTaskConfigCreateManyAndReturnArgs} args - Arguments to create many ScheduledTaskConfigs.
   * @example
   * // Create many ScheduledTaskConfigs
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ScheduledTaskConfigs and only return the `id`
   * const scheduledTaskConfigWithIdOnly = await prisma.scheduledTaskConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ScheduledTaskConfigCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigCreateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a ScheduledTaskConfig.
   * @param {ScheduledTaskConfigDeleteArgs} args - Arguments to delete one ScheduledTaskConfig.
   * @example
   * // Delete one ScheduledTaskConfig
   * const ScheduledTaskConfig = await prisma.scheduledTaskConfig.delete({
   *   where: {
   *     // ... filter to delete one ScheduledTaskConfig
   *   }
   * })
   *
   */
  delete<T extends ScheduledTaskConfigDeleteArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one ScheduledTaskConfig.
   * @param {ScheduledTaskConfigUpdateArgs} args - Arguments to update one ScheduledTaskConfig.
   * @example
   * // Update one ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ScheduledTaskConfigUpdateArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more ScheduledTaskConfigs.
   * @param {ScheduledTaskConfigDeleteManyArgs} args - Arguments to filter ScheduledTaskConfigs to delete.
   * @example
   * // Delete a few ScheduledTaskConfigs
   * const { count } = await prisma.scheduledTaskConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ScheduledTaskConfigDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ScheduledTaskConfigDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduledTaskConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ScheduledTaskConfigs
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ScheduledTaskConfigUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ScheduledTaskConfigs and returns the data updated in the database.
   * @param {ScheduledTaskConfigUpdateManyAndReturnArgs} args - Arguments to update many ScheduledTaskConfigs.
   * @example
   * // Update many ScheduledTaskConfigs
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ScheduledTaskConfigs and only return the `id`
   * const scheduledTaskConfigWithIdOnly = await prisma.scheduledTaskConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ScheduledTaskConfigUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one ScheduledTaskConfig.
   * @param {ScheduledTaskConfigUpsertArgs} args - Arguments to update or create a ScheduledTaskConfig.
   * @example
   * // Update or create a ScheduledTaskConfig
   * const scheduledTaskConfig = await prisma.scheduledTaskConfig.upsert({
   *   create: {
   *     // ... data to create a ScheduledTaskConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ScheduledTaskConfig we want to update
   *   }
   * })
   */
  upsert<T extends ScheduledTaskConfigUpsertArgs>(
    args: Prisma.SelectSubset<T, ScheduledTaskConfigUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__ScheduledTaskConfigClient<
    runtime.Types.Result.GetResult<
      Prisma.$ScheduledTaskConfigPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of ScheduledTaskConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigCountArgs} args - Arguments to filter ScheduledTaskConfigs to count.
   * @example
   * // Count the number of ScheduledTaskConfigs
   * const count = await prisma.scheduledTaskConfig.count({
   *   where: {
   *     // ... the filter for the ScheduledTaskConfigs we want to count
   *   }
   * })
   **/
  count<T extends ScheduledTaskConfigCountArgs>(
    args?: Prisma.Subset<T, ScheduledTaskConfigCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ScheduledTaskConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ScheduledTaskConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ScheduledTaskConfigAggregateArgs>(
    args: Prisma.Subset<T, ScheduledTaskConfigAggregateArgs>
  ): Prisma.PrismaPromise<GetScheduledTaskConfigAggregateType<T>>

  /**
   * Group by ScheduledTaskConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ScheduledTaskConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ScheduledTaskConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: ScheduledTaskConfigGroupByArgs['orderBy'] }
      : { orderBy?: ScheduledTaskConfigGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields])
  >(
    args: Prisma.SubsetIntersection<T, ScheduledTaskConfigGroupByArgs, OrderByArg> & InputErrors
  ): {} extends InputErrors
    ? GetScheduledTaskConfigGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the ScheduledTaskConfig model
   */
  readonly fields: ScheduledTaskConfigFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for ScheduledTaskConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ScheduledTaskConfigClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {}
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the ScheduledTaskConfig model
 */
export interface ScheduledTaskConfigFieldRefs {
  readonly id: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly taskName: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly displayName: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly cronExpression: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly enabled: Prisma.FieldRef<'ScheduledTaskConfig', 'Boolean'>
  readonly lastRunAt: Prisma.FieldRef<'ScheduledTaskConfig', 'DateTime'>
  readonly lastStatus: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly lastError: Prisma.FieldRef<'ScheduledTaskConfig', 'String'>
  readonly createdAt: Prisma.FieldRef<'ScheduledTaskConfig', 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<'ScheduledTaskConfig', 'DateTime'>
}

// Custom InputTypes
/**
 * ScheduledTaskConfig findUnique
 */
export type ScheduledTaskConfigFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledTaskConfig to fetch.
   */
  where: Prisma.ScheduledTaskConfigWhereUniqueInput
}

/**
 * ScheduledTaskConfig findUniqueOrThrow
 */
export type ScheduledTaskConfigFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledTaskConfig to fetch.
   */
  where: Prisma.ScheduledTaskConfigWhereUniqueInput
}

/**
 * ScheduledTaskConfig findFirst
 */
export type ScheduledTaskConfigFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledTaskConfig to fetch.
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ScheduledTaskConfigs to fetch.
   */
  orderBy?:
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ScheduledTaskConfigs.
   */
  cursor?: Prisma.ScheduledTaskConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ScheduledTaskConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ScheduledTaskConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ScheduledTaskConfigs.
   */
  distinct?: Prisma.ScheduledTaskConfigScalarFieldEnum | Prisma.ScheduledTaskConfigScalarFieldEnum[]
}

/**
 * ScheduledTaskConfig findFirstOrThrow
 */
export type ScheduledTaskConfigFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledTaskConfig to fetch.
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ScheduledTaskConfigs to fetch.
   */
  orderBy?:
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ScheduledTaskConfigs.
   */
  cursor?: Prisma.ScheduledTaskConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ScheduledTaskConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ScheduledTaskConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ScheduledTaskConfigs.
   */
  distinct?: Prisma.ScheduledTaskConfigScalarFieldEnum | Prisma.ScheduledTaskConfigScalarFieldEnum[]
}

/**
 * ScheduledTaskConfig findMany
 */
export type ScheduledTaskConfigFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter, which ScheduledTaskConfigs to fetch.
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ScheduledTaskConfigs to fetch.
   */
  orderBy?:
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput
    | Prisma.ScheduledTaskConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ScheduledTaskConfigs.
   */
  cursor?: Prisma.ScheduledTaskConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ScheduledTaskConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ScheduledTaskConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ScheduledTaskConfigs.
   */
  distinct?: Prisma.ScheduledTaskConfigScalarFieldEnum | Prisma.ScheduledTaskConfigScalarFieldEnum[]
}

/**
 * ScheduledTaskConfig create
 */
export type ScheduledTaskConfigCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a ScheduledTaskConfig.
   */
  data: Prisma.XOR<
    Prisma.ScheduledTaskConfigCreateInput,
    Prisma.ScheduledTaskConfigUncheckedCreateInput
  >
}

/**
 * ScheduledTaskConfig createMany
 */
export type ScheduledTaskConfigCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to create many ScheduledTaskConfigs.
   */
  data: Prisma.ScheduledTaskConfigCreateManyInput | Prisma.ScheduledTaskConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduledTaskConfig createManyAndReturn
 */
export type ScheduledTaskConfigCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * The data used to create many ScheduledTaskConfigs.
   */
  data: Prisma.ScheduledTaskConfigCreateManyInput | Prisma.ScheduledTaskConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ScheduledTaskConfig update
 */
export type ScheduledTaskConfigUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a ScheduledTaskConfig.
   */
  data: Prisma.XOR<
    Prisma.ScheduledTaskConfigUpdateInput,
    Prisma.ScheduledTaskConfigUncheckedUpdateInput
  >
  /**
   * Choose, which ScheduledTaskConfig to update.
   */
  where: Prisma.ScheduledTaskConfigWhereUniqueInput
}

/**
 * ScheduledTaskConfig updateMany
 */
export type ScheduledTaskConfigUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * The data used to update ScheduledTaskConfigs.
   */
  data: Prisma.XOR<
    Prisma.ScheduledTaskConfigUpdateManyMutationInput,
    Prisma.ScheduledTaskConfigUncheckedUpdateManyInput
  >
  /**
   * Filter which ScheduledTaskConfigs to update
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * Limit how many ScheduledTaskConfigs to update.
   */
  limit?: number
}

/**
 * ScheduledTaskConfig updateManyAndReturn
 */
export type ScheduledTaskConfigUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * The data used to update ScheduledTaskConfigs.
   */
  data: Prisma.XOR<
    Prisma.ScheduledTaskConfigUpdateManyMutationInput,
    Prisma.ScheduledTaskConfigUncheckedUpdateManyInput
  >
  /**
   * Filter which ScheduledTaskConfigs to update
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * Limit how many ScheduledTaskConfigs to update.
   */
  limit?: number
}

/**
 * ScheduledTaskConfig upsert
 */
export type ScheduledTaskConfigUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the ScheduledTaskConfig to update in case it exists.
   */
  where: Prisma.ScheduledTaskConfigWhereUniqueInput
  /**
   * In case the ScheduledTaskConfig found by the `where` argument doesn't exist, create a new ScheduledTaskConfig with this data.
   */
  create: Prisma.XOR<
    Prisma.ScheduledTaskConfigCreateInput,
    Prisma.ScheduledTaskConfigUncheckedCreateInput
  >
  /**
   * In case the ScheduledTaskConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.ScheduledTaskConfigUpdateInput,
    Prisma.ScheduledTaskConfigUncheckedUpdateInput
  >
}

/**
 * ScheduledTaskConfig delete
 */
export type ScheduledTaskConfigDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
  /**
   * Filter which ScheduledTaskConfig to delete.
   */
  where: Prisma.ScheduledTaskConfigWhereUniqueInput
}

/**
 * ScheduledTaskConfig deleteMany
 */
export type ScheduledTaskConfigDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Filter which ScheduledTaskConfigs to delete
   */
  where?: Prisma.ScheduledTaskConfigWhereInput
  /**
   * Limit how many ScheduledTaskConfigs to delete.
   */
  limit?: number
}

/**
 * ScheduledTaskConfig without action
 */
export type ScheduledTaskConfigDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs
> = {
  /**
   * Select specific fields to fetch from the ScheduledTaskConfig
   */
  select?: Prisma.ScheduledTaskConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ScheduledTaskConfig
   */
  omit?: Prisma.ScheduledTaskConfigOmit<ExtArgs> | null
}
