<template>
  <div class="min-h-screen bg-[oklch(12%_0.015_155)] text-gray-100 flex flex-col">
    <header
      class="sticky top-0 z-50 bg-[oklch(12%_0.015_155)]/90 backdrop-blur border-b border-white/8"
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex items-center justify-between h-16">
          <NuxtLink to="/" class="flex items-center hover:opacity-90 transition-opacity">
            <img
              src="/media/logo_with_text_cropped.webp"
              alt="Journey Endurance"
              width="702"
              height="135"
              loading="eager"
              decoding="async"
              class="h-12 w-auto object-contain"
            />
          </NuxtLink>
          <div class="flex items-center gap-4">
            <div class="hidden sm:flex items-center gap-2">
              <UButton
                v-if="route.path !== '/login'"
                to="/login"
                variant="ghost"
                color="neutral"
                size="sm"
              >
                Sign In
              </UButton>
              <UButton v-if="route.path !== '/join'" to="/join" color="primary" size="sm">
                Get Started
              </UButton>
            </div>
            <ColorModeButton />
            <UPopover class="sm:hidden">
              <UButton
                icon="i-lucide-menu"
                color="neutral"
                variant="ghost"
                aria-label="Open menu"
              />
              <template #content>
                <div class="p-3 w-44 flex flex-col gap-2">
                  <UButton
                    v-if="route.path !== '/login'"
                    to="/login"
                    variant="ghost"
                    color="neutral"
                    block
                  >
                    Sign In
                  </UButton>
                  <UButton v-if="route.path !== '/join'" to="/join" color="primary" block>
                    Get Started
                  </UButton>
                </div>
              </template>
            </UPopover>
          </div>
        </div>
      </div>
    </header>

    <main class="flex-1">
      <slot />

      <SharePageCTA />
    </main>

    <!-- Footer -->
    <footer
      class="mt-auto py-10 px-6 border-t border-white/8 text-center bg-[oklch(14%_0.018_155)]"
    >
      <p class="text-sm font-medium text-gray-400">
        Generated by
        <a href="https://journeyendurance.ca/" class="font-bold text-primary-400 hover:underline"
          >Journey Endurance</a
        >
      </p>
      <p class="text-xs font-bold uppercase tracking-widest text-gray-400 mt-2">
        Adaptive Endurance Intelligence
      </p>
    </footer>
  </div>
</template>

<script setup lang="ts">
  const route = useRoute()
</script>
